package com.tdkj.service.CreditVillage;

import com.tdkj.model.CreditVillage;

import java.util.List;

/**
 * Created by len on 2019-04-29.
 */
public interface CreditVillageService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cvg001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    int insert(CreditVillage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    int insertSelective(CreditVillage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    CreditVillage selectByPrimaryKey(String cvg001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CreditVillage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CreditVillage record);

    /**
     * 根据aab301 查询信用乡村信息
     * @param aab301
     * @return
     */
    public List<CreditVillage> queryCreditVillageByAab301(CreditVillage creditVillage,String startRecord,String pageSize) ;


    /**
     * 根据行政区划查询总条数
     * @param aab301
     * @return
     */
    public String queryAllByAab301(CreditVillage creditVillage);


}
