server:
  servlet:
    session:
      timeout: 17200s  #session超时时间，s表示单位是秒
      cookie:         #保存sessionID的cookie
        name: TSESSIONID
        path: /

spring:
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB


  jpa:
    database: oracle
  datasource:
    # 使用c3p0数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@47.110.128.122:1521:orcl
    username: c##sxjzfprs
    password: SE13o7EFD4823#D2
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 17
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 60000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 ,wall
    filters: stat,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: false

  thymeleaf:
    cache: true     #开发过程建议设为为false；生产环境设为true



logging:

  file: target/app.log
  level:
    ROOT: WARN
    cn.devmgr: info
    org.springframework: info
    org.thymeleaf.TemplateEngine: info



endpoints:
  shutdown:
    #启用shutdown
    enabled: true
    #禁用密码验证
    sensitive: false


# pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: false # 如果没有数据  返回空 而非最后一页的数据
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check



