package com.tdkj.service.PovertyAlleviationBase;

import com.tdkj.model.PovertyAlleviationBase;

import java.util.List;

/**
 * Created by len on 2019-04-29.
 */
public interface PovertyAlleviationBaseService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poverty_alleviation_base
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String pab001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poverty_alleviation_base
     *
     * @mbggenerated
     */
    int insert(PovertyAlleviationBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poverty_alleviation_base
     *
     * @mbggenerated
     */
    int insertSelective(PovertyAlleviationBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poverty_alleviation_base
     *
     * @mbggenerated
     */
    PovertyAlleviationBase selectByPrimaryKey(String pab001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poverty_alleviation_base
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PovertyAlleviationBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poverty_alleviation_base
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PovertyAlleviationBase record);

    /**
     * 根据aab301 查询扶贫基地信息
     * @param aab301
     * @return
     */
    public List<PovertyAlleviationBase> queryPovertyAlleviationBaseByAab301(PovertyAlleviationBase povertyAlleviationBase,String startRecord,String pageSize);

    /**
     * 根据行政区划查询 总条数
     * @param aab301
     * @return
     */
    public String queryAllByAab301(PovertyAlleviationBase povertyAlleviationBase);



    ///*****************待完善扶贫基地信息**********************************************************************************************************

    /**
     * 根据aab301   查询  待完善 扶贫基地信息
     * @return
     */
    public List<PovertyAlleviationBase> querytobeCompletePovertyAlleviationBaseByAab301(PovertyAlleviationBase povertyAlleviationBase,String startRecord,String pageSize);

    /**
     * 根据行政区划查询 待完善 扶贫基地 总条数
     * @return
     */
    public String queryAlltobeCompleteByAab301(PovertyAlleviationBase povertyAlleviationBase);

}
