package com.tdkj.dao.Param;

import com.tdkj.model.Aa10;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface Aa10Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa10
     *
     * @mbggenerated
     */
    int insert(Aa10 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa10
     *
     * @mbggenerated
     */
    int insertSelective(Aa10 record);


    /**
     * 根据aaa100查询下拉框中的参数值
     * @param aaa100
     * @return
     */
    List<Aa10> queryAa10ByAaa100(String aaa100);

    /**
     * 根据aaa100查询下拉框中的参数值
     * @param aaa100list
     * @return
     */
    List<Aa10> queryAllAa10list();


    /**
     * 根据aaa100查询下拉框中的参数值
     * @param aaa100
     * @return
     */
    List<Aa10> queryAa10ByAaa100Type(@Param("aaa100")String aaa100,@Param("aaa103") String aaa103);
}