package com.tdkj.model;

public class Aa10 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa10.aaz093
     *
     * @mbggenerated
     */
    private Long aaz093;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa10.aaa027
     *
     * @mbggenerated
     */
    private String aaa027;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa10.aaa100
     *
     * @mbggenerated
     */
    private String aaa100;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa10.aaa102
     *
     * @mbggenerated
     */
    private String aaa102;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa10.aaa103
     *
     * @mbggenerated
     */
    private String aaa103;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa10.aaa105
     *
     * @mbggenerated
     */
    private String aaa105;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa10.aae100
     *
     * @mbggenerated
     */
    private String aae100;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa10.aaa104
     *
     * @mbggenerated
     */
    private String aaa104;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa10.prseno
     *
     * @mbggenerated
     */
    private Long prseno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa10.aaz093
     *
     * @return the value of aa10.aaz093
     *
     * @mbggenerated
     */
    public Long getAaz093() {
        return aaz093;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa10.aaz093
     *
     * @param aaz093 the value for aa10.aaz093
     *
     * @mbggenerated
     */
    public void setAaz093(Long aaz093) {
        this.aaz093 = aaz093;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa10.aaa027
     *
     * @return the value of aa10.aaa027
     *
     * @mbggenerated
     */
    public String getAaa027() {
        return aaa027;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa10.aaa027
     *
     * @param aaa027 the value for aa10.aaa027
     *
     * @mbggenerated
     */
    public void setAaa027(String aaa027) {
        this.aaa027 = aaa027 == null ? null : aaa027.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa10.aaa100
     *
     * @return the value of aa10.aaa100
     *
     * @mbggenerated
     */
    public String getAaa100() {
        return aaa100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa10.aaa100
     *
     * @param aaa100 the value for aa10.aaa100
     *
     * @mbggenerated
     */
    public void setAaa100(String aaa100) {
        this.aaa100 = aaa100 == null ? null : aaa100.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa10.aaa102
     *
     * @return the value of aa10.aaa102
     *
     * @mbggenerated
     */
    public String getAaa102() {
        return aaa102;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa10.aaa102
     *
     * @param aaa102 the value for aa10.aaa102
     *
     * @mbggenerated
     */
    public void setAaa102(String aaa102) {
        this.aaa102 = aaa102 == null ? null : aaa102.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa10.aaa103
     *
     * @return the value of aa10.aaa103
     *
     * @mbggenerated
     */
    public String getAaa103() {
        return aaa103;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa10.aaa103
     *
     * @param aaa103 the value for aa10.aaa103
     *
     * @mbggenerated
     */
    public void setAaa103(String aaa103) {
        this.aaa103 = aaa103 == null ? null : aaa103.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa10.aaa105
     *
     * @return the value of aa10.aaa105
     *
     * @mbggenerated
     */
    public String getAaa105() {
        return aaa105;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa10.aaa105
     *
     * @param aaa105 the value for aa10.aaa105
     *
     * @mbggenerated
     */
    public void setAaa105(String aaa105) {
        this.aaa105 = aaa105 == null ? null : aaa105.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa10.aae100
     *
     * @return the value of aa10.aae100
     *
     * @mbggenerated
     */
    public String getAae100() {
        return aae100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa10.aae100
     *
     * @param aae100 the value for aa10.aae100
     *
     * @mbggenerated
     */
    public void setAae100(String aae100) {
        this.aae100 = aae100 == null ? null : aae100.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa10.aaa104
     *
     * @return the value of aa10.aaa104
     *
     * @mbggenerated
     */
    public String getAaa104() {
        return aaa104;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa10.aaa104
     *
     * @param aaa104 the value for aa10.aaa104
     *
     * @mbggenerated
     */
    public void setAaa104(String aaa104) {
        this.aaa104 = aaa104 == null ? null : aaa104.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa10.prseno
     *
     * @return the value of aa10.prseno
     *
     * @mbggenerated
     */
    public Long getPrseno() {
        return prseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa10.prseno
     *
     * @param prseno the value for aa10.prseno
     *
     * @mbggenerated
     */
    public void setPrseno(Long prseno) {
        this.prseno = prseno;
    }
}