package com.tdkj.model;

import java.util.Date;

public class CentralizedSettlements {

    private String cts001;

    private String aab301;

    private String cts002;

    private String cts003;

    private Date aae036;

    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae011;

    private String aae012;

    private String aae013;

    private String aae014;

    private Date aae015;

    private String rn;

    private String deleteby;

    private Date deletedate;

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    public String getRn() {
        return rn;
    }

    public void setRn(String rn) {
        this.rn = rn;
    }

    public Date getAae015() {
        return aae015;
    }

    public void setAae015(Date aae015) {
        this.aae015 = aae015;
    }

    public Date getAae036() {
        return aae036;
    }

    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae011() {
        return aae011;
    }

    public void setAae011(String aae011) {
        this.aae011 = aae011;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getAae013() {
        return aae013;
    }

    public void setAae013(String aae013) {
        this.aae013 = aae013;
    }

    public String getAae014() {
        return aae014;
    }

    public void setAae014(String aae014) {
        this.aae014 = aae014;
    }

    public String getCts001() {
        return cts001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTRALIZED_SETTLEMENTS.CTS001
     *
     * @param cts001 the value for CENTRALIZED_SETTLEMENTS.CTS001
     *
     * @mbggenerated
     */
    public void setCts001(String cts001) {
        this.cts001 = cts001 == null ? null : cts001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTRALIZED_SETTLEMENTS.AAB301
     *
     * @return the value of CENTRALIZED_SETTLEMENTS.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTRALIZED_SETTLEMENTS.AAB301
     *
     * @param aab301 the value for CENTRALIZED_SETTLEMENTS.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTRALIZED_SETTLEMENTS.CTS002
     *
     * @return the value of CENTRALIZED_SETTLEMENTS.CTS002
     *
     * @mbggenerated
     */
    public String getCts002() {
        return cts002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTRALIZED_SETTLEMENTS.CTS002
     *
     * @param cts002 the value for CENTRALIZED_SETTLEMENTS.CTS002
     *
     * @mbggenerated
     */
    public void setCts002(String cts002) {
        this.cts002 = cts002 == null ? null : cts002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CENTRALIZED_SETTLEMENTS.CTS003
     *
     * @return the value of CENTRALIZED_SETTLEMENTS.CTS003
     *
     * @mbggenerated
     */
    public String getCts003() {
        return cts003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CENTRALIZED_SETTLEMENTS.CTS003
     *
     * @param cts003 the value for CENTRALIZED_SETTLEMENTS.CTS003
     *
     * @mbggenerated
     */
    public void setCts003(String cts003) {
        this.cts003 = cts003 == null ? null : cts003.trim();
    }
}