package com.tdkj.model;

import java.util.Date;

public class CommunityFactory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF001
     *
     * @mbggenerated
     */
    private String ctf001;
    private String ctf012;
    private String ctf013;
    private String ctf014;

    private String rn;

    private String deleteby;

    private Date deletedate;

    private String ctf015;

    private String ctf016;
    private String taizhang;

    private String istaizahang;//判断是不是台账进来查询的，如果则不为空    虚拟字段

    private String istobecomplete; //是否待完善列表查询    虚拟字段

    private String ctf017;

    private String ctf018;

    private String ctf019;

    private String ctf020;

    public String getCtf017() {
        return ctf017;
    }

    public void setCtf017(String ctf017) {
        this.ctf017 = ctf017;
    }

    public String getCtf018() {
        return ctf018;
    }

    public void setCtf018(String ctf018) {
        this.ctf018 = ctf018;
    }

    public String getCtf019() {
        return ctf019;
    }

    public void setCtf019(String ctf019) {
        this.ctf019 = ctf019;
    }

    public String getCtf020() {
        return ctf020;
    }

    public void setCtf020(String ctf020) {
        this.ctf020 = ctf020;
    }

    public String getIstobecomplete() {
        return istobecomplete;
    }

    public void setIstobecomplete(String istobecomplete) {
        this.istobecomplete = istobecomplete;
    }

    public String getIstaizahang() {
        return istaizahang;
    }

    public String getTaizhang() {
        return taizhang;
    }

    public void setTaizhang(String taizhang) {
        this.taizhang = taizhang;
    }

    public void setIstaizahang(String istaizahang) {
        this.istaizahang = istaizahang;
    }

    public String getCtf016() {
        return ctf016;
    }

    public void setCtf016(String ctf016) {
        this.ctf016 = ctf016;
    }

    public String getCtf015() {
        return ctf015;
    }

    public void setCtf015(String ctf015) {
        this.ctf015 = ctf015;
    }

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    public String getRn() {
        return rn;
    }

    public void setRn(String rn) {
        this.rn = rn;
    }

    public String getCtf012() {
        return ctf012;
    }

    public void setCtf012(String ctf012) {
        this.ctf012 = ctf012;
    }

    public String getCtf013() {
        return ctf013;
    }

    public void setCtf013(String ctf013) {
        this.ctf013 = ctf013;
    }

    public String getCtf014() {
        return ctf014;
    }

    public void setCtf014(String ctf014) {
        this.ctf014 = ctf014;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF002
     *
     * @mbggenerated
     */
    private String ctf002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF003
     *
     * @mbggenerated
     */
    private String ctf003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF004
     *
     * @mbggenerated
     */
    private String ctf004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF005
     *
     * @mbggenerated
     */
    private String ctf005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF006
     *
     * @mbggenerated
     */
    private String ctf006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF007
     *
     * @mbggenerated
     */
    private Integer ctf007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF008
     *
     * @mbggenerated
     */
    private Integer ctf008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF009
     *
     * @mbggenerated
     */
    private String ctf009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF010
     *
     * @mbggenerated
     */
    private String ctf010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.CTF011
     *
     * @mbggenerated
     */
    private String ctf011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.AAB301
     *
     * @mbggenerated
     */
    private String aab301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_factory.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;

    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae012;

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF001
     *
     * @return the value of community_factory.CTF001
     *
     * @mbggenerated
     */
    public String getCtf001() {
        return ctf001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF001
     *
     * @param ctf001 the value for community_factory.CTF001
     *
     * @mbggenerated
     */
    public void setCtf001(String ctf001) {
        this.ctf001 = ctf001 == null ? null : ctf001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF002
     *
     * @return the value of community_factory.CTF002
     *
     * @mbggenerated
     */
    public String getCtf002() {
        return ctf002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF002
     *
     * @param ctf002 the value for community_factory.CTF002
     *
     * @mbggenerated
     */
    public void setCtf002(String ctf002) {
        this.ctf002 = ctf002 == null ? null : ctf002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF003
     *
     * @return the value of community_factory.CTF003
     *
     * @mbggenerated
     */
    public String getCtf003() {
        return ctf003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF003
     *
     * @param ctf003 the value for community_factory.CTF003
     *
     * @mbggenerated
     */
    public void setCtf003(String ctf003) {
        this.ctf003 = ctf003 == null ? null : ctf003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF004
     *
     * @return the value of community_factory.CTF004
     *
     * @mbggenerated
     */
    public String getCtf004() {
        return ctf004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF004
     *
     * @param ctf004 the value for community_factory.CTF004
     *
     * @mbggenerated
     */
    public void setCtf004(String ctf004) {
        this.ctf004 = ctf004 == null ? null : ctf004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF005
     *
     * @return the value of community_factory.CTF005
     *
     * @mbggenerated
     */
    public String getCtf005() {
        return ctf005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF005
     *
     * @param ctf005 the value for community_factory.CTF005
     *
     * @mbggenerated
     */
    public void setCtf005(String ctf005) {
        this.ctf005 = ctf005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF006
     *
     * @return the value of community_factory.CTF006
     *
     * @mbggenerated
     */
    public String getCtf006() {
        return ctf006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF006
     *
     * @param ctf006 the value for community_factory.CTF006
     *
     * @mbggenerated
     */
    public void setCtf006(String ctf006) {
        this.ctf006 = ctf006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF007
     *
     * @return the value of community_factory.CTF007
     *
     * @mbggenerated
     */
    public Integer getCtf007() {
        return ctf007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF007
     *
     * @param ctf007 the value for community_factory.CTF007
     *
     * @mbggenerated
     */
    public void setCtf007(Integer ctf007) {
        this.ctf007 = ctf007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF008
     *
     * @return the value of community_factory.CTF008
     *
     * @mbggenerated
     */
    public Integer getCtf008() {
        return ctf008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF008
     *
     * @param ctf008 the value for community_factory.CTF008
     *
     * @mbggenerated
     */
    public void setCtf008(Integer ctf008) {
        this.ctf008 = ctf008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF009
     *
     * @return the value of community_factory.CTF009
     *
     * @mbggenerated
     */
    public String getCtf009() {
        return ctf009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF009
     *
     * @param ctf009 the value for community_factory.CTF009
     *
     * @mbggenerated
     */
    public void setCtf009(String ctf009) {
        this.ctf009 = ctf009 == null ? null : ctf009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF010
     *
     * @return the value of community_factory.CTF010
     *
     * @mbggenerated
     */
    public String getCtf010() {
        return ctf010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF010
     *
     * @param ctf010 the value for community_factory.CTF010
     *
     * @mbggenerated
     */
    public void setCtf010(String ctf010) {
        this.ctf010 = ctf010 == null ? null : ctf010.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.CTF011
     *
     * @return the value of community_factory.CTF011
     *
     * @mbggenerated
     */
    public String getCtf011() {
        return ctf011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.CTF011
     *
     * @param ctf011 the value for community_factory.CTF011
     *
     * @mbggenerated
     */
    public void setCtf011(String ctf011) {
        this.ctf011 = ctf011 == null ? null : ctf011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.AAB301
     *
     * @return the value of community_factory.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.AAB301
     *
     * @param aab301 the value for community_factory.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.AAE011
     *
     * @return the value of community_factory.AAE011
     *
     * @mbggenerated
     */
    public String getAae011() {
        return aae011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.AAE011
     *
     * @param aae011 the value for community_factory.AAE011
     *
     * @mbggenerated
     */
    public void setAae011(String aae011) {
        this.aae011 = aae011 == null ? null : aae011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_factory.AAE036
     *
     * @return the value of community_factory.AAE036
     *
     * @mbggenerated
     */
    public Date getAae036() {
        return aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_factory.AAE036
     *
     * @param aae036 the value for community_factory.AAE036
     *
     * @mbggenerated
     */
    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }


}