package com.tdkj.model;

import java.math.BigDecimal;
import java.util.Date;

public class CreditVillage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG001
     *
     * @mbggenerated
     */
    private String cvg001;
    private String cvg013;
    private String cvg014;
    private String cvg015;
    private String cvg016;
    private String deleteby;

    private String istobecomplete; //是否待完善列表查询    虚拟字段

    private Date deletedate;
    private String cvg017;
    private String cvg018;

    public String getIstobecomplete() {
        return istobecomplete;
    }

    public void setIstobecomplete(String istobecomplete) {
        this.istobecomplete = istobecomplete;
    }

    public String getCvg017() {
        return cvg017;
    }

    public void setCvg017(String cvg017) {
        this.cvg017 = cvg017;
    }

    public String getCvg018() {
        return cvg018;
    }

    public void setCvg018(String cvg018) {
        this.cvg018 = cvg018;
    }

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    public String getCvg013() {
        return cvg013;
    }

    public void setCvg013(String cvg013) {
        this.cvg013 = cvg013;
    }

    public String getCvg014() {
        return cvg014;
    }

    public void setCvg014(String cvg014) {
        this.cvg014 = cvg014;
    }

    public String getCvg015() {
        return cvg015;
    }

    public void setCvg015(String cvg015) {
        this.cvg015 = cvg015;
    }

    public String getCvg016() {
        return cvg016;
    }

    public void setCvg016(String cvg016) {
        this.cvg016 = cvg016;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG002
     *
     * @mbggenerated
     */
    private String cvg002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.AAB301
     *
     * @mbggenerated
     */
    private String aab301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG004
     *
     * @mbggenerated
     */
    private String cvg004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG005
     *
     * @mbggenerated
     */
    private Integer cvg005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG006
     *
     * @mbggenerated
     */
    private Integer cvg006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG007
     *
     * @mbggenerated
     */
    private BigDecimal cvg007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG008
     *
     * @mbggenerated
     */
    private BigDecimal cvg008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG009
     *
     * @mbggenerated
     */
    private String cvg009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG010
     *
     * @mbggenerated
     */
    private String cvg010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG011
     *
     * @mbggenerated
     */
    private String cvg011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_village.CVG012
     *
     * @mbggenerated
     */
    private String cvg012;

    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae012;

    private String rn;

    public String getRn() {
        return rn;
    }

    public void setRn(String rn) {
        this.rn = rn;
    }

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG001
     *
     * @return the value of credit_village.CVG001
     *
     * @mbggenerated
     */
    public String getCvg001() {
        return cvg001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG001
     *
     * @param cvg001 the value for credit_village.CVG001
     *
     * @mbggenerated
     */
    public void setCvg001(String cvg001) {
        this.cvg001 = cvg001 == null ? null : cvg001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG002
     *
     * @return the value of credit_village.CVG002
     *
     * @mbggenerated
     */
    public String getCvg002() {
        return cvg002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG002
     *
     * @param cvg002 the value for credit_village.CVG002
     *
     * @mbggenerated
     */
    public void setCvg002(String cvg002) {
        this.cvg002 = cvg002 == null ? null : cvg002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.AAE036
     *
     * @return the value of credit_village.AAE036
     *
     * @mbggenerated
     */
    public Date getAae036() {
        return aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.AAE036
     *
     * @param aae036 the value for credit_village.AAE036
     *
     * @mbggenerated
     */
    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.AAB301
     *
     * @return the value of credit_village.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.AAB301
     *
     * @param aab301 the value for credit_village.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG004
     *
     * @return the value of credit_village.CVG004
     *
     * @mbggenerated
     */
    public String getCvg004() {
        return cvg004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG004
     *
     * @param cvg004 the value for credit_village.CVG004
     *
     * @mbggenerated
     */
    public void setCvg004(String cvg004) {
        this.cvg004 = cvg004 == null ? null : cvg004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG005
     *
     * @return the value of credit_village.CVG005
     *
     * @mbggenerated
     */
    public Integer getCvg005() {
        return cvg005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG005
     *
     * @param cvg005 the value for credit_village.CVG005
     *
     * @mbggenerated
     */
    public void setCvg005(Integer cvg005) {
        this.cvg005 = cvg005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG006
     *
     * @return the value of credit_village.CVG006
     *
     * @mbggenerated
     */
    public Integer getCvg006() {
        return cvg006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG006
     *
     * @param cvg006 the value for credit_village.CVG006
     *
     * @mbggenerated
     */
    public void setCvg006(Integer cvg006) {
        this.cvg006 = cvg006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG007
     *
     * @return the value of credit_village.CVG007
     *
     * @mbggenerated
     */
    public BigDecimal getCvg007() {
        return cvg007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG007
     *
     * @param cvg007 the value for credit_village.CVG007
     *
     * @mbggenerated
     */
    public void setCvg007(BigDecimal cvg007) {
        this.cvg007 = cvg007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG008
     *
     * @return the value of credit_village.CVG008
     *
     * @mbggenerated
     */
    public BigDecimal getCvg008() {
        return cvg008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG008
     *
     * @param cvg008 the value for credit_village.CVG008
     *
     * @mbggenerated
     */
    public void setCvg008(BigDecimal cvg008) {
        this.cvg008 = cvg008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG009
     *
     * @return the value of credit_village.CVG009
     *
     * @mbggenerated
     */
    public String getCvg009() {
        return cvg009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG009
     *
     * @param cvg009 the value for credit_village.CVG009
     *
     * @mbggenerated
     */
    public void setCvg009(String cvg009) {
        this.cvg009 = cvg009 == null ? null : cvg009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG010
     *
     * @return the value of credit_village.CVG010
     *
     * @mbggenerated
     */
    public String getCvg010() {
        return cvg010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG010
     *
     * @param cvg010 the value for credit_village.CVG010
     *
     * @mbggenerated
     */
    public void setCvg010(String cvg010) {
        this.cvg010 = cvg010 == null ? null : cvg010.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.AAE011
     *
     * @return the value of credit_village.AAE011
     *
     * @mbggenerated
     */
    public String getAae011() {
        return aae011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.AAE011
     *
     * @param aae011 the value for credit_village.AAE011
     *
     * @mbggenerated
     */
    public void setAae011(String aae011) {
        this.aae011 = aae011 == null ? null : aae011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG011
     *
     * @return the value of credit_village.CVG011
     *
     * @mbggenerated
     */
    public String getCvg011() {
        return cvg011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG011
     *
     * @param cvg011 the value for credit_village.CVG011
     *
     * @mbggenerated
     */
    public void setCvg011(String cvg011) {
        this.cvg011 = cvg011 == null ? null : cvg011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_village.CVG012
     *
     * @return the value of credit_village.CVG012
     *
     * @mbggenerated
     */
    public String getCvg012() {
        return cvg012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_village.CVG012
     *
     * @param cvg012 the value for credit_village.CVG012
     *
     * @mbggenerated
     */
    public void setCvg012(String cvg012) {
        this.cvg012 = cvg012 == null ? null : cvg012.trim();
    }
}