package com.tdkj.model;

import java.util.Date;

public class EmploymentSituation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS001
     *
     * @mbggenerated
     */
    private String eys001;

    private String eys002;
    private String eys016;
    private String eys017;
    private String eys018;
    private String eys019;
    private String eys020;
    private String eys021;
    private String eys022;
    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae012;

    private String isnew;

    private String rn;//排序

    private String startage;    //年龄开始  虚拟字段
    private String endage;//年龄结束  虚拟字段
    private String deleteby;
    private String identification;
    private Date deletedate;

    private String eys023;//个人领取社保补贴
    private String eys024;

    private String phd013;
    private String phd014;
    private String plf004;
    private String plf005;

    public String getIdentification() {
        return identification;
    }

    public void setIdentification(String identification) {
        this.identification = identification;
    }

    public String getPhd013() {
        return phd013;
    }

    public void setPhd013(String phd013) {
        this.phd013 = phd013;
    }

    public String getPhd014() {
        return phd014;
    }

    public void setPhd014(String phd014) {
        this.phd014 = phd014;
    }

    public String getPlf004() {
        return plf004;
    }

    public void setPlf004(String plf004) {
        this.plf004 = plf004;
    }

    public String getPlf005() {
        return plf005;
    }

    public void setPlf005(String plf005) {
        this.plf005 = plf005;
    }

    public String getEys024() {
        return eys024;
    }

    public void setEys024(String eys024) {
        this.eys024 = eys024;
    }

    public String getEys023() {
        return eys023;
    }

    public void setEys023(String eys023) {
        this.eys023 = eys023;
    }

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    public String getRn() {
        return rn;
    }

    public void setRn(String rn) {
        this.rn = rn;
    }

    public String getStartage() {
        return startage;
    }

    public void setStartage(String startage) {
        this.startage = startage;
    }

    public String getEndage() {
        return endage;
    }

    public void setEndage(String endage) {
        this.endage = endage;
    }

    public String getIsnew() {
        return isnew;
    }

    public void setIsnew(String isnew) {
        this.isnew = isnew;
    }

    public String getEys017() {
        return eys017;
    }

    public void setEys017(String eys017) {
        this.eys017 = eys017;
    }

    public String getEys018() {
        return eys018;
    }

    public void setEys018(String eys018) {
        this.eys018 = eys018;
    }

    public String getEys019() {
        return eys019;
    }

    public void setEys019(String eys019) {
        this.eys019 = eys019;
    }

    public String getEys020() {
        return eys020;
    }

    public void setEys020(String eys020) {
        this.eys020 = eys020;
    }

    public String getEys021() {
        return eys021;
    }

    public void setEys021(String eys021) {
        this.eys021 = eys021;
    }

    public String getEys002() {
        return eys002;
    }

    public void setEys002(String eys002) {
        this.eys002 = eys002;
    }



    public String getEys016() {
        return eys016;
    }

    public void setEys016(String eys016) {
        this.eys016 = eys016;
    }

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS003
     *
     * @mbggenerated
     */
    private String eys003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS004
     *
     * @mbggenerated
     */
    private String eys004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS005
     *
     * @mbggenerated
     */
    private String eys005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS006
     *
     * @mbggenerated
     */
    private String eys006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS007
     *
     * @mbggenerated
     */
    private String eys007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS008
     *
     * @mbggenerated
     */
    private String eys008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS009
     *
     * @mbggenerated
     */
    private String eys009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS010
     *
     * @mbggenerated
     */
    private String eys010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS011
     *
     * @mbggenerated
     */
    private String eys011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS012
     *
     * @mbggenerated
     */
    private String eys012;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS013
     *
     * @mbggenerated
     */
    private String eys013;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS014
     *
     * @mbggenerated
     */
    private String eys014;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.AAB301
     *
     * @mbggenerated
     */
    private String aab301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_situation.EYS015
     *
     * @mbggenerated
     */
    private String eys015;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS001
     *
     * @return the value of employment_situation.EYS001
     *
     * @mbggenerated
     */
    public String getEys001() {
        return eys001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS001
     *
     * @param eys001 the value for employment_situation.EYS001
     *
     * @mbggenerated
     */
    public void setEys001(String eys001) {
        this.eys001 = eys001 == null ? null : eys001.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS003
     *
     * @return the value of employment_situation.EYS003
     *
     * @mbggenerated
     */
    public String getEys003() {
        return eys003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS003
     *
     * @param eys003 the value for employment_situation.EYS003
     *
     * @mbggenerated
     */
    public void setEys003(String eys003) {
        this.eys003 = eys003 == null ? null : eys003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS004
     *
     * @return the value of employment_situation.EYS004
     *
     * @mbggenerated
     */
    public String getEys004() {
        return eys004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS004
     *
     * @param eys004 the value for employment_situation.EYS004
     *
     * @mbggenerated
     */
    public void setEys004(String eys004) {
        this.eys004 = eys004 == null ? null : eys004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS005
     *
     * @return the value of employment_situation.EYS005
     *
     * @mbggenerated
     */
    public String getEys005() {
        return eys005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS005
     *
     * @param eys005 the value for employment_situation.EYS005
     *
     * @mbggenerated
     */
    public void setEys005(String eys005) {
        this.eys005 = eys005 == null ? null : eys005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS006
     *
     * @return the value of employment_situation.EYS006
     *
     * @mbggenerated
     */
    public String getEys006() {
        return eys006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS006
     *
     * @param eys006 the value for employment_situation.EYS006
     *
     * @mbggenerated
     */
    public void setEys006(String eys006) {
        this.eys006 = eys006 == null ? null : eys006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS007
     *
     * @return the value of employment_situation.EYS007
     *
     * @mbggenerated
     */
    public String getEys007() {
        return eys007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS007
     *
     * @param eys007 the value for employment_situation.EYS007
     *
     * @mbggenerated
     */
    public void setEys007(String eys007) {
        this.eys007 = eys007 == null ? null : eys007.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS008
     *
     * @return the value of employment_situation.EYS008
     *
     * @mbggenerated
     */
    public String getEys008() {
        return eys008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS008
     *
     * @param eys008 the value for employment_situation.EYS008
     *
     * @mbggenerated
     */
    public void setEys008(String eys008) {
        this.eys008 = eys008 == null ? null : eys008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS009
     *
     * @return the value of employment_situation.EYS009
     *
     * @mbggenerated
     */
    public String getEys009() {
        return eys009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS009
     *
     * @param eys009 the value for employment_situation.EYS009
     *
     * @mbggenerated
     */
    public void setEys009(String eys009) {
        this.eys009 = eys009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS010
     *
     * @return the value of employment_situation.EYS010
     *
     * @mbggenerated
     */
    public String getEys010() {
        return eys010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS010
     *
     * @param eys010 the value for employment_situation.EYS010
     *
     * @mbggenerated
     */
    public void setEys010(String eys010) {
        this.eys010 = eys010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS011
     *
     * @return the value of employment_situation.EYS011
     *
     * @mbggenerated
     */
    public String getEys011() {
        return eys011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS011
     *
     * @param eys011 the value for employment_situation.EYS011
     *
     * @mbggenerated
     */
    public void setEys011(String eys011) {
        this.eys011 = eys011 == null ? null : eys011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS012
     *
     * @return the value of employment_situation.EYS012
     *
     * @mbggenerated
     */
    public String getEys012() {
        return eys012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS012
     *
     * @param eys012 the value for employment_situation.EYS012
     *
     * @mbggenerated
     */
    public void setEys012(String eys012) {
        this.eys012 = eys012 == null ? null : eys012.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS013
     *
     * @return the value of employment_situation.EYS013
     *
     * @mbggenerated
     */
    public String getEys013() {
        return eys013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS013
     *
     * @param eys013 the value for employment_situation.EYS013
     *
     * @mbggenerated
     */
    public void setEys013(String eys013) {
        this.eys013 = eys013 == null ? null : eys013.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS014
     *
     * @return the value of employment_situation.EYS014
     *
     * @mbggenerated
     */
    public String getEys014() {
        return eys014;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS014
     *
     * @param eys014 the value for employment_situation.EYS014
     *
     * @mbggenerated
     */
    public void setEys014(String eys014) {
        this.eys014 = eys014 == null ? null : eys014.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.AAB301
     *
     * @return the value of employment_situation.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.AAB301
     *
     * @param aab301 the value for employment_situation.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.AAE011
     *
     * @return the value of employment_situation.AAE011
     *
     * @mbggenerated
     */
    public String getAae011() {
        return aae011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.AAE011
     *
     * @param aae011 the value for employment_situation.AAE011
     *
     * @mbggenerated
     */
    public void setAae011(String aae011) {
        this.aae011 = aae011 == null ? null : aae011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.AAE036
     *
     * @return the value of employment_situation.AAE036
     *
     * @mbggenerated
     */
    public Date getAae036() {
        return aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.AAE036
     *
     * @param aae036 the value for employment_situation.AAE036
     *
     * @mbggenerated
     */
    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_situation.EYS015
     *
     * @return the value of employment_situation.EYS015
     *
     * @mbggenerated
     */
    public String getEys015() {
        return eys015;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_situation.EYS015
     *
     * @param eys015 the value for employment_situation.EYS015
     *
     * @mbggenerated
     */
    public void setEys015(String eys015) {
        this.eys015 = eys015 == null ? null : eys015.trim();
    }

    public String getEys022() {
        return eys022;
    }

    public void setEys022(String eys022) {
        this.eys022 = eys022;
    }
}