package com.tdkj.model;

import java.util.Date;

public class EmUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.XZQ_ID
     *
     * @mbggenerated
     */
    private String xzqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.XZQMC
     *
     * @mbggenerated
     */
    private String xzqmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.ZJHM
     *
     * @mbggenerated
     */
    private String zjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.LOGINNAME
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.USERTYPE
     *
     * @mbggenerated
     */
    private Integer usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.ZT
     *
     * @mbggenerated
     */
    private Integer zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_user.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.USER_ID
     *
     * @return the value of em_user.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.USER_ID
     *
     * @param userId the value for em_user.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.XZQ_ID
     *
     * @return the value of em_user.XZQ_ID
     *
     * @mbggenerated
     */
    public String getXzqId() {
        return xzqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.XZQ_ID
     *
     * @param xzqId the value for em_user.XZQ_ID
     *
     * @mbggenerated
     */
    public void setXzqId(String xzqId) {
        this.xzqId = xzqId == null ? null : xzqId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.XZQMC
     *
     * @return the value of em_user.XZQMC
     *
     * @mbggenerated
     */
    public String getXzqmc() {
        return xzqmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.XZQMC
     *
     * @param xzqmc the value for em_user.XZQMC
     *
     * @mbggenerated
     */
    public void setXzqmc(String xzqmc) {
        this.xzqmc = xzqmc == null ? null : xzqmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.USERNAME
     *
     * @return the value of em_user.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.USERNAME
     *
     * @param username the value for em_user.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.ZJHM
     *
     * @return the value of em_user.ZJHM
     *
     * @mbggenerated
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.ZJHM
     *
     * @param zjhm the value for em_user.ZJHM
     *
     * @mbggenerated
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm == null ? null : zjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.LOGINNAME
     *
     * @return the value of em_user.LOGINNAME
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.LOGINNAME
     *
     * @param loginname the value for em_user.LOGINNAME
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.PASSWORD
     *
     * @return the value of em_user.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.PASSWORD
     *
     * @param password the value for em_user.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.PHONE
     *
     * @return the value of em_user.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.PHONE
     *
     * @param phone the value for em_user.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.USERTYPE
     *
     * @return the value of em_user.USERTYPE
     *
     * @mbggenerated
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.USERTYPE
     *
     * @param usertype the value for em_user.USERTYPE
     *
     * @mbggenerated
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.CREATETIME
     *
     * @return the value of em_user.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.CREATETIME
     *
     * @param createtime the value for em_user.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.ZT
     *
     * @return the value of em_user.ZT
     *
     * @mbggenerated
     */
    public Integer getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.ZT
     *
     * @param zt the value for em_user.ZT
     *
     * @mbggenerated
     */
    public void setZt(Integer zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.BZ
     *
     * @return the value of em_user.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.BZ
     *
     * @param bz the value for em_user.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }
}