package com.tdkj.model;

public class EmXzqView {

    private String groupid;
    private String isParent;
    private String parentid;
    private String name;
    private String groupname;

    public String getGroupid() {
        return groupid;
    }

    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    public String getIsParent() {
        return isParent;
    }

    public void setIsParent(String isParent) {
        this.isParent = isParent;
    }

    public String getParentid() {
        return parentid;
    }

    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGroupname() {
        return groupname;
    }

    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQ_ID5
     *
     * @mbggenerated
     */
    private String xzqId5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQMC5
     *
     * @mbggenerated
     */
    private String xzqmc5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQJB
     *
     * @mbggenerated
     */
    private String xzqjb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.SSXZQ
     *
     * @mbggenerated
     */
    private String ssxzq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.P_XZQID
     *
     * @mbggenerated
     */
    private String pXzqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQ_ID4
     *
     * @mbggenerated
     */
    private String xzqId4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQMC4
     *
     * @mbggenerated
     */
    private String xzqmc4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQ_ID3
     *
     * @mbggenerated
     */
    private String xzqId3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQMC3
     *
     * @mbggenerated
     */
    private String xzqmc3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQ_ID2
     *
     * @mbggenerated
     */
    private String xzqId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQMC2
     *
     * @mbggenerated
     */
    private String xzqmc2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQ_ID1
     *
     * @mbggenerated
     */
    private String xzqId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_xzq_view.XZQMC1
     *
     * @mbggenerated
     */
    private String xzqmc1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQ_ID5
     *
     * @return the value of em_xzq_view.XZQ_ID5
     *
     * @mbggenerated
     */
    public String getXzqId5() {
        return xzqId5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQ_ID5
     *
     * @param xzqId5 the value for em_xzq_view.XZQ_ID5
     *
     * @mbggenerated
     */
    public void setXzqId5(String xzqId5) {
        this.xzqId5 = xzqId5 == null ? null : xzqId5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQMC5
     *
     * @return the value of em_xzq_view.XZQMC5
     *
     * @mbggenerated
     */
    public String getXzqmc5() {
        return xzqmc5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQMC5
     *
     * @param xzqmc5 the value for em_xzq_view.XZQMC5
     *
     * @mbggenerated
     */
    public void setXzqmc5(String xzqmc5) {
        this.xzqmc5 = xzqmc5 == null ? null : xzqmc5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQJB
     *
     * @return the value of em_xzq_view.XZQJB
     *
     * @mbggenerated
     */
    public String getXzqjb() {
        return xzqjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQJB
     *
     * @param xzqjb the value for em_xzq_view.XZQJB
     *
     * @mbggenerated
     */
    public void setXzqjb(String xzqjb) {
        this.xzqjb = xzqjb == null ? null : xzqjb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.SSXZQ
     *
     * @return the value of em_xzq_view.SSXZQ
     *
     * @mbggenerated
     */
    public String getSsxzq() {
        return ssxzq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.SSXZQ
     *
     * @param ssxzq the value for em_xzq_view.SSXZQ
     *
     * @mbggenerated
     */
    public void setSsxzq(String ssxzq) {
        this.ssxzq = ssxzq == null ? null : ssxzq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.P_XZQID
     *
     * @return the value of em_xzq_view.P_XZQID
     *
     * @mbggenerated
     */
    public String getpXzqid() {
        return pXzqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.P_XZQID
     *
     * @param pXzqid the value for em_xzq_view.P_XZQID
     *
     * @mbggenerated
     */
    public void setpXzqid(String pXzqid) {
        this.pXzqid = pXzqid == null ? null : pXzqid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQ_ID4
     *
     * @return the value of em_xzq_view.XZQ_ID4
     *
     * @mbggenerated
     */
    public String getXzqId4() {
        return xzqId4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQ_ID4
     *
     * @param xzqId4 the value for em_xzq_view.XZQ_ID4
     *
     * @mbggenerated
     */
    public void setXzqId4(String xzqId4) {
        this.xzqId4 = xzqId4 == null ? null : xzqId4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQMC4
     *
     * @return the value of em_xzq_view.XZQMC4
     *
     * @mbggenerated
     */
    public String getXzqmc4() {
        return xzqmc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQMC4
     *
     * @param xzqmc4 the value for em_xzq_view.XZQMC4
     *
     * @mbggenerated
     */
    public void setXzqmc4(String xzqmc4) {
        this.xzqmc4 = xzqmc4 == null ? null : xzqmc4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQ_ID3
     *
     * @return the value of em_xzq_view.XZQ_ID3
     *
     * @mbggenerated
     */
    public String getXzqId3() {
        return xzqId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQ_ID3
     *
     * @param xzqId3 the value for em_xzq_view.XZQ_ID3
     *
     * @mbggenerated
     */
    public void setXzqId3(String xzqId3) {
        this.xzqId3 = xzqId3 == null ? null : xzqId3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQMC3
     *
     * @return the value of em_xzq_view.XZQMC3
     *
     * @mbggenerated
     */
    public String getXzqmc3() {
        return xzqmc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQMC3
     *
     * @param xzqmc3 the value for em_xzq_view.XZQMC3
     *
     * @mbggenerated
     */
    public void setXzqmc3(String xzqmc3) {
        this.xzqmc3 = xzqmc3 == null ? null : xzqmc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQ_ID2
     *
     * @return the value of em_xzq_view.XZQ_ID2
     *
     * @mbggenerated
     */
    public String getXzqId2() {
        return xzqId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQ_ID2
     *
     * @param xzqId2 the value for em_xzq_view.XZQ_ID2
     *
     * @mbggenerated
     */
    public void setXzqId2(String xzqId2) {
        this.xzqId2 = xzqId2 == null ? null : xzqId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQMC2
     *
     * @return the value of em_xzq_view.XZQMC2
     *
     * @mbggenerated
     */
    public String getXzqmc2() {
        return xzqmc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQMC2
     *
     * @param xzqmc2 the value for em_xzq_view.XZQMC2
     *
     * @mbggenerated
     */
    public void setXzqmc2(String xzqmc2) {
        this.xzqmc2 = xzqmc2 == null ? null : xzqmc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQ_ID1
     *
     * @return the value of em_xzq_view.XZQ_ID1
     *
     * @mbggenerated
     */
    public String getXzqId1() {
        return xzqId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQ_ID1
     *
     * @param xzqId1 the value for em_xzq_view.XZQ_ID1
     *
     * @mbggenerated
     */
    public void setXzqId1(String xzqId1) {
        this.xzqId1 = xzqId1 == null ? null : xzqId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_xzq_view.XZQMC1
     *
     * @return the value of em_xzq_view.XZQMC1
     *
     * @mbggenerated
     */
    public String getXzqmc1() {
        return xzqmc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_xzq_view.XZQMC1
     *
     * @param xzqmc1 the value for em_xzq_view.XZQMC1
     *
     * @mbggenerated
     */
    public void setXzqmc1(String xzqmc1) {
        this.xzqmc1 = xzqmc1 == null ? null : xzqmc1.trim();
    }
}