package com.tdkj.model;

import java.util.Date;
public class Entrepreneurship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.EPP001
     *
     * @mbggenerated
     */
    private String epp001;
    private String epp010;
    private String epp011;
    private String epp012;
    private String epp013;
    private String epp014;
    private String epp015;
    private String epp016;

    private String isnew;
    private String deleteby;

    private Date deletedate;

    private String phd013;
    private String phd014;
    private String plf004;
    private String plf005;

    public String getPhd013() {
        return phd013;
    }

    public void setPhd013(String phd013) {
        this.phd013 = phd013;
    }

    public String getPhd014() {
        return phd014;
    }

    public void setPhd014(String phd014) {
        this.phd014 = phd014;
    }

    public String getPlf004() {
        return plf004;
    }

    public void setPlf004(String plf004) {
        this.plf004 = plf004;
    }

    public String getPlf005() {
        return plf005;
    }

    public void setPlf005(String plf005) {
        this.plf005 = plf005;
    }

    public String getEpp016() {
        return epp016;
    }

    public void setEpp016(String epp016) {
        this.epp016 = epp016;
    }

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    public String getIsnew() {
        return isnew;
    }

    public void setIsnew(String isnew) {
        this.isnew = isnew;
    }

    public String getEpp014() {
        return epp014;
    }

    public void setEpp014(String epp014) {
        this.epp014 = epp014;
    }

    public String getEpp015() {
        return epp015;
    }

    public void setEpp015(String epp015) {
        this.epp015 = epp015;
    }




    public String getEpp010() {
        return epp010;
    }

    public void setEpp010(String epp010) {
        this.epp010 = epp010;
    }

    public String getEpp011() {
        return epp011;
    }

    public void setEpp011(String epp011) {
        this.epp011 = epp011;
    }

    public String getEpp012() {
        return epp012;
    }

    public void setEpp012(String epp012) {
        this.epp012 = epp012;
    }

    public String getEpp013() {
        return epp013;
    }

    public void setEpp013(String epp013) {
        this.epp013 = epp013;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.EPP002
     *
     * @mbggenerated
     */
    private String epp002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.EPP003
     *
     * @mbggenerated
     */
    private String epp003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.EPP004
     *
     * @mbggenerated
     */
    private String epp004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.EPP005
     *
     * @mbggenerated
     */
    private String epp005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.EPP006
     *
     * @mbggenerated
     */
    private String epp006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.EPP007
     *
     * @mbggenerated
     */
    private String epp007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.EPP008
     *
     * @mbggenerated
     */
    private String epp008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.EPP009
     *
     * @mbggenerated
     */
    private String epp009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.AAB301
     *
     * @mbggenerated
     */
    private String aab301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrepreneurship.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;

    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae012;

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.EPP001
     *
     * @return the value of entrepreneurship.EPP001
     *
     * @mbggenerated
     */
    public String getEpp001() {
        return epp001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.EPP001
     *
     * @param epp001 the value for entrepreneurship.EPP001
     *
     * @mbggenerated
     */
    public void setEpp001(String epp001) {
        this.epp001 = epp001 == null ? null : epp001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.EPP002
     *
     * @return the value of entrepreneurship.EPP002
     *
     * @mbggenerated
     */
    public String getEpp002() {
        return epp002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.EPP002
     *
     * @param epp002 the value for entrepreneurship.EPP002
     *
     * @mbggenerated
     */
    public void setEpp002(String epp002) {
        this.epp002 = epp002 == null ? null : epp002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.EPP003
     *
     * @return the value of entrepreneurship.EPP003
     *
     * @mbggenerated
     */
    public String getEpp003() {
        return epp003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.EPP003
     *
     * @param epp003 the value for entrepreneurship.EPP003
     *
     * @mbggenerated
     */
    public void setEpp003(String epp003) {
        this.epp003 = epp003 == null ? null : epp003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.EPP004
     *
     * @return the value of entrepreneurship.EPP004
     *
     * @mbggenerated
     */
    public String getEpp004() {
        return epp004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.EPP004
     *
     * @param epp004 the value for entrepreneurship.EPP004
     *
     * @mbggenerated
     */
    public void setEpp004(String epp004) {
        this.epp004 = epp004 == null ? null : epp004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.EPP005
     *
     * @return the value of entrepreneurship.EPP005
     *
     * @mbggenerated
     */
    public String getEpp005() {
        return epp005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.EPP005
     *
     * @param epp005 the value for entrepreneurship.EPP005
     *
     * @mbggenerated
     */
    public void setEpp005(String epp005) {
        this.epp005 = epp005 == null ? null : epp005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.EPP006
     *
     * @return the value of entrepreneurship.EPP006
     *
     * @mbggenerated
     */
    public String getEpp006() {
        return epp006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.EPP006
     *
     * @param epp006 the value for entrepreneurship.EPP006
     *
     * @mbggenerated
     */
    public void setEpp006(String epp006) {
        this.epp006 = epp006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.EPP007
     *
     * @return the value of entrepreneurship.EPP007
     *
     * @mbggenerated
     */
    public String getEpp007() {
        return epp007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.EPP007
     *
     * @param epp007 the value for entrepreneurship.EPP007
     *
     * @mbggenerated
     */
    public void setEpp007(String epp007) {
        this.epp007 = epp007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.EPP008
     *
     * @return the value of entrepreneurship.EPP008
     *
     * @mbggenerated
     */
    public String getEpp008() {
        return epp008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.EPP008
     *
     * @param epp008 the value for entrepreneurship.EPP008
     *
     * @mbggenerated
     */
    public void setEpp008(String epp008) {
        this.epp008 = epp008 == null ? null : epp008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.EPP009
     *
     * @return the value of entrepreneurship.EPP009
     *
     * @mbggenerated
     */
    public String getEpp009() {
        return epp009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.EPP009
     *
     * @param epp009 the value for entrepreneurship.EPP009
     *
     * @mbggenerated
     */
    public void setEpp009(String epp009) {
        this.epp009 = epp009 == null ? null : epp009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.AAB301
     *
     * @return the value of entrepreneurship.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.AAB301
     *
     * @param aab301 the value for entrepreneurship.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.AAE011
     *
     * @return the value of entrepreneurship.AAE011
     *
     * @mbggenerated
     */
    public String getAae011() {
        return aae011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.AAE011
     *
     * @param aae011 the value for entrepreneurship.AAE011
     *
     * @mbggenerated
     */
    public void setAae011(String aae011) {
        this.aae011 = aae011 == null ? null : aae011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrepreneurship.AAE036
     *
     * @return the value of entrepreneurship.AAE036
     *
     * @mbggenerated
     */
    public Date getAae036() {
        return aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrepreneurship.AAE036
     *
     * @param aae036 the value for entrepreneurship.AAE036
     *
     * @mbggenerated
     */
    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }
}