package com.tdkj.model;



import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
/*implements UserDetails*/
public class FpUser {

   /* private Collection<? extends GrantedAuthority> authorities;

    public void setAuthorities(Collection<? extends GrantedAuthority> authorities) {
        this.authorities = authorities;
    }

    @Override
    public boolean isAccountNonExpired() {
        return false;
    }

    @Override
    public boolean isAccountNonLocked() {
        return false;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return false;
    }

    @Override
    public boolean isEnabled() {
        return false;
    }
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return null;
    }*/



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.ID
     *
     * @mbggenerated
     */
    private String id;

    private String rn;

    public String getRn() {
        return rn;
    }

    public void setRn(String rn) {
        this.rn = rn;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.REALNAME
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.USERTYPE
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.COMENT
     *
     * @mbggenerated
     */
    private String coment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.CREATEDDATE
     *
     * @mbggenerated
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.UPDATEDDATE
     *
     * @mbggenerated
     */
    private Date updateddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.FLAG
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.MOBILEPHOME
     *
     * @mbggenerated
     */
    private String mobilephome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.IDCARD
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.IMAGEPATH
     *
     * @mbggenerated
     */
    private String imagepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.AGE
     *
     * @mbggenerated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FP_USER.AAB301
     *
     * @mbggenerated
     */
    private String aab301;

    private String info;//临时字段，数据库中没有

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.ID
     *
     * @return the value of FP_USER.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.ID
     *
     * @param id the value for FP_USER.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.USERNAME
     *
     * @return the value of FP_USER.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.USERNAME
     *
     * @param username the value for FP_USER.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.PASSWORD
     *
     * @return the value of FP_USER.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.PASSWORD
     *
     * @param password the value for FP_USER.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.REALNAME
     *
     * @return the value of FP_USER.REALNAME
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.REALNAME
     *
     * @param realname the value for FP_USER.REALNAME
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.USERTYPE
     *
     * @return the value of FP_USER.USERTYPE
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.USERTYPE
     *
     * @param usertype the value for FP_USER.USERTYPE
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.COMENT
     *
     * @return the value of FP_USER.COMENT
     *
     * @mbggenerated
     */
    public String getComent() {
        return coment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.COMENT
     *
     * @param coment the value for FP_USER.COMENT
     *
     * @mbggenerated
     */
    public void setComent(String coment) {
        this.coment = coment == null ? null : coment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.CREATEDDATE
     *
     * @return the value of FP_USER.CREATEDDATE
     *
     * @mbggenerated
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.CREATEDDATE
     *
     * @param createddate the value for FP_USER.CREATEDDATE
     *
     * @mbggenerated
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.UPDATEDDATE
     *
     * @return the value of FP_USER.UPDATEDDATE
     *
     * @mbggenerated
     */
    public Date getUpdateddate() {
        return updateddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.UPDATEDDATE
     *
     * @param updateddate the value for FP_USER.UPDATEDDATE
     *
     * @mbggenerated
     */
    public void setUpdateddate(Date updateddate) {
        this.updateddate = updateddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.FLAG
     *
     * @return the value of FP_USER.FLAG
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.FLAG
     *
     * @param flag the value for FP_USER.FLAG
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.MOBILEPHOME
     *
     * @return the value of FP_USER.MOBILEPHOME
     *
     * @mbggenerated
     */
    public String getMobilephome() {
        return mobilephome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.MOBILEPHOME
     *
     * @param mobilephome the value for FP_USER.MOBILEPHOME
     *
     * @mbggenerated
     */
    public void setMobilephome(String mobilephome) {
        this.mobilephome = mobilephome == null ? null : mobilephome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.IDCARD
     *
     * @return the value of FP_USER.IDCARD
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.IDCARD
     *
     * @param idcard the value for FP_USER.IDCARD
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.IMAGEPATH
     *
     * @return the value of FP_USER.IMAGEPATH
     *
     * @mbggenerated
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.IMAGEPATH
     *
     * @param imagepath the value for FP_USER.IMAGEPATH
     *
     * @mbggenerated
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath == null ? null : imagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.SEX
     *
     * @return the value of FP_USER.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.SEX
     *
     * @param sex the value for FP_USER.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.AGE
     *
     * @return the value of FP_USER.AGE
     *
     * @mbggenerated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.AGE
     *
     * @param age the value for FP_USER.AGE
     *
     * @mbggenerated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FP_USER.AAB301
     *
     * @return the value of FP_USER.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FP_USER.AAB301
     *
     * @param aab301 the value for FP_USER.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }
}