package com.tdkj.model;

import java.util.Date;

public class IncubatorBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB001
     *
     * @mbggenerated
     */
    private String ibb001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.AAB301
     *
     * @mbggenerated
     */
    private String aab301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB003
     *
     * @mbggenerated
     */
    private String ibb003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB004
     *
     * @mbggenerated
     */
    private String ibb004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB005
     *
     * @mbggenerated
     */
    private String ibb005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB006
     *
     * @mbggenerated
     */
    private String ibb006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB007
     *
     * @mbggenerated
     */
    private String ibb007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB008
     *
     * @mbggenerated
     */
    private String ibb008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB009
     *
     * @mbggenerated
     */
    private String ibb009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB010
     *
     * @mbggenerated
     */
    private Integer ibb010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB011
     *
     * @mbggenerated
     */
    private Integer ibb011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB012
     *
     * @mbggenerated
     */
    private Integer ibb012;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB013
     *
     * @mbggenerated
     */
    private Integer ibb013;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB014
     *
     * @mbggenerated
     */
    private String ibb014;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.IBB015
     *
     * @mbggenerated
     */
    private String ibb015;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column incubator_base.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;


    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae012;

    private String rn;  //虚拟字段  序号
    private String deleteby;

    private Date deletedate;

    private String ibb016;

    private String istobecomplete;//虚拟字段

    public String getIstobecomplete() {
        return istobecomplete;
    }

    public void setIstobecomplete(String istobecomplete) {
        this.istobecomplete = istobecomplete;
    }


    public String getIbb016() {
        return ibb016;
    }

    public void setIbb016(String ibb016) {
        this.ibb016 = ibb016;
    }

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    public String getRn() {
        return rn;
    }

    public void setRn(String rn) {
        this.rn = rn;
    }

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB001
     *
     * @return the value of incubator_base.IBB001
     *
     * @mbggenerated
     */
    public String getIbb001() {
        return ibb001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB001
     *
     * @param ibb001 the value for incubator_base.IBB001
     *
     * @mbggenerated
     */
    public void setIbb001(String ibb001) {
        this.ibb001 = ibb001 == null ? null : ibb001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.AAB301
     *
     * @return the value of incubator_base.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.AAB301
     *
     * @param aab301 the value for incubator_base.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB003
     *
     * @return the value of incubator_base.IBB003
     *
     * @mbggenerated
     */
    public String getIbb003() {
        return ibb003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB003
     *
     * @param ibb003 the value for incubator_base.IBB003
     *
     * @mbggenerated
     */
    public void setIbb003(String ibb003) {
        this.ibb003 = ibb003 == null ? null : ibb003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB004
     *
     * @return the value of incubator_base.IBB004
     *
     * @mbggenerated
     */
    public String getIbb004() {
        return ibb004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB004
     *
     * @param ibb004 the value for incubator_base.IBB004
     *
     * @mbggenerated
     */
    public void setIbb004(String ibb004) {
        this.ibb004 = ibb004 == null ? null : ibb004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB005
     *
     * @return the value of incubator_base.IBB005
     *
     * @mbggenerated
     */
    public String getIbb005() {
        return ibb005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB005
     *
     * @param ibb005 the value for incubator_base.IBB005
     *
     * @mbggenerated
     */
    public void setIbb005(String ibb005) {
        this.ibb005 = ibb005 == null ? null : ibb005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB006
     *
     * @return the value of incubator_base.IBB006
     *
     * @mbggenerated
     */
    public String getIbb006() {
        return ibb006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB006
     *
     * @param ibb006 the value for incubator_base.IBB006
     *
     * @mbggenerated
     */
    public void setIbb006(String ibb006) {
        this.ibb006 = ibb006 == null ? null : ibb006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB007
     *
     * @return the value of incubator_base.IBB007
     *
     * @mbggenerated
     */
    public String getIbb007() {
        return ibb007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB007
     *
     * @param ibb007 the value for incubator_base.IBB007
     *
     * @mbggenerated
     */
    public void setIbb007(String ibb007) {
        this.ibb007 = ibb007 == null ? null : ibb007.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB008
     *
     * @return the value of incubator_base.IBB008
     *
     * @mbggenerated
     */
    public String getIbb008() {
        return ibb008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB008
     *
     * @param ibb008 the value for incubator_base.IBB008
     *
     * @mbggenerated
     */
    public void setIbb008(String ibb008) {
        this.ibb008 = ibb008 == null ? null : ibb008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB009
     *
     * @return the value of incubator_base.IBB009
     *
     * @mbggenerated
     */
    public String getIbb009() {
        return ibb009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB009
     *
     * @param ibb009 the value for incubator_base.IBB009
     *
     * @mbggenerated
     */
    public void setIbb009(String ibb009) {
        this.ibb009 = ibb009 == null ? null : ibb009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB010
     *
     * @return the value of incubator_base.IBB010
     *
     * @mbggenerated
     */
    public Integer getIbb010() {
        return ibb010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB010
     *
     * @param ibb010 the value for incubator_base.IBB010
     *
     * @mbggenerated
     */
    public void setIbb010(Integer ibb010) {
        this.ibb010 = ibb010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB011
     *
     * @return the value of incubator_base.IBB011
     *
     * @mbggenerated
     */
    public Integer getIbb011() {
        return ibb011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB011
     *
     * @param ibb011 the value for incubator_base.IBB011
     *
     * @mbggenerated
     */
    public void setIbb011(Integer ibb011) {
        this.ibb011 = ibb011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB012
     *
     * @return the value of incubator_base.IBB012
     *
     * @mbggenerated
     */
    public Integer getIbb012() {
        return ibb012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB012
     *
     * @param ibb012 the value for incubator_base.IBB012
     *
     * @mbggenerated
     */
    public void setIbb012(Integer ibb012) {
        this.ibb012 = ibb012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB013
     *
     * @return the value of incubator_base.IBB013
     *
     * @mbggenerated
     */
    public Integer getIbb013() {
        return ibb013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB013
     *
     * @param ibb013 the value for incubator_base.IBB013
     *
     * @mbggenerated
     */
    public void setIbb013(Integer ibb013) {
        this.ibb013 = ibb013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB014
     *
     * @return the value of incubator_base.IBB014
     *
     * @mbggenerated
     */
    public String getIbb014() {
        return ibb014;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB014
     *
     * @param ibb014 the value for incubator_base.IBB014
     *
     * @mbggenerated
     */
    public void setIbb014(String ibb014) {
        this.ibb014 = ibb014 == null ? null : ibb014.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.IBB015
     *
     * @return the value of incubator_base.IBB015
     *
     * @mbggenerated
     */
    public String getIbb015() {
        return ibb015;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.IBB015
     *
     * @param ibb015 the value for incubator_base.IBB015
     *
     * @mbggenerated
     */
    public void setIbb015(String ibb015) {
        this.ibb015 = ibb015 == null ? null : ibb015.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.AAE011
     *
     * @return the value of incubator_base.AAE011
     *
     * @mbggenerated
     */
    public String getAae011() {
        return aae011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.AAE011
     *
     * @param aae011 the value for incubator_base.AAE011
     *
     * @mbggenerated
     */
    public void setAae011(String aae011) {
        this.aae011 = aae011 == null ? null : aae011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column incubator_base.AAE036
     *
     * @return the value of incubator_base.AAE036
     *
     * @mbggenerated
     */
    public Date getAae036() {
        return aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column incubator_base.AAE036
     *
     * @param aae036 the value for incubator_base.AAE036
     *
     * @mbggenerated
     */
    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }
}