package com.tdkj.model;

import java.util.Date;

public class Information {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.IFT001
     *
     * @mbggenerated
     */
    private String ift001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.AAB301
     *
     * @mbggenerated
     */
    private String aab301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.IFT003
     *
     * @mbggenerated
     */
    private Integer ift003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.IFT004
     *
     * @mbggenerated
     */
    private Integer ift004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.IFT005
     *
     * @mbggenerated
     */
    private Integer ift005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.IFT006
     *
     * @mbggenerated
     */
    private Integer ift006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.IFT007
     *
     * @mbggenerated
     */
    private Integer ift007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.IFT008
     *
     * @mbggenerated
     */
    private String ift008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.IFT009
     *
     * @mbggenerated
     */
    private String ift009;


    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae012;

    private String rn;
    private String deleteby;

    private Date deletedate;

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    public String getRn() {
        return rn;
    }

    public void setRn(String rn) {
        this.rn = rn;
    }

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.IFT001
     *
     * @return the value of information.IFT001
     *
     * @mbggenerated
     */
    public String getIft001() {
        return ift001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.IFT001
     *
     * @param ift001 the value for information.IFT001
     *
     * @mbggenerated
     */
    public void setIft001(String ift001) {
        this.ift001 = ift001 == null ? null : ift001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.AAB301
     *
     * @return the value of information.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.AAB301
     *
     * @param aab301 the value for information.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.IFT003
     *
     * @return the value of information.IFT003
     *
     * @mbggenerated
     */
    public Integer getIft003() {
        return ift003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.IFT003
     *
     * @param ift003 the value for information.IFT003
     *
     * @mbggenerated
     */
    public void setIft003(Integer ift003) {
        this.ift003 = ift003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.IFT004
     *
     * @return the value of information.IFT004
     *
     * @mbggenerated
     */
    public Integer getIft004() {
        return ift004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.IFT004
     *
     * @param ift004 the value for information.IFT004
     *
     * @mbggenerated
     */
    public void setIft004(Integer ift004) {
        this.ift004 = ift004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.IFT005
     *
     * @return the value of information.IFT005
     *
     * @mbggenerated
     */
    public Integer getIft005() {
        return ift005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.IFT005
     *
     * @param ift005 the value for information.IFT005
     *
     * @mbggenerated
     */
    public void setIft005(Integer ift005) {
        this.ift005 = ift005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.IFT006
     *
     * @return the value of information.IFT006
     *
     * @mbggenerated
     */
    public Integer getIft006() {
        return ift006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.IFT006
     *
     * @param ift006 the value for information.IFT006
     *
     * @mbggenerated
     */
    public void setIft006(Integer ift006) {
        this.ift006 = ift006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.IFT007
     *
     * @return the value of information.IFT007
     *
     * @mbggenerated
     */
    public Integer getIft007() {
        return ift007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.IFT007
     *
     * @param ift007 the value for information.IFT007
     *
     * @mbggenerated
     */
    public void setIft007(Integer ift007) {
        this.ift007 = ift007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.IFT008
     *
     * @return the value of information.IFT008
     *
     * @mbggenerated
     */
    public String getIft008() {
        return ift008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.IFT008
     *
     * @param ift008 the value for information.IFT008
     *
     * @mbggenerated
     */
    public void setIft008(String ift008) {
        this.ift008 = ift008 == null ? null : ift008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.AAE036
     *
     * @return the value of information.AAE036
     *
     * @mbggenerated
     */
    public Date getAae036() {
        return aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.AAE036
     *
     * @param aae036 the value for information.AAE036
     *
     * @mbggenerated
     */
    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.AAE011
     *
     * @return the value of information.AAE011
     *
     * @mbggenerated
     */
    public String getAae011() {
        return aae011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.AAE011
     *
     * @param aae011 the value for information.AAE011
     *
     * @mbggenerated
     */
    public void setAae011(String aae011) {
        this.aae011 = aae011 == null ? null : aae011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.IFT009
     *
     * @return the value of information.IFT009
     *
     * @mbggenerated
     */
    public String getIft009() {
        return ift009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.IFT009
     *
     * @param ift009 the value for information.IFT009
     *
     * @mbggenerated
     */
    public void setIft009(String ift009) {
        this.ift009 = ift009 == null ? null : ift009.trim();
    }
}