package com.tdkj.model;

import java.util.Date;

public class PoorChangeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.PCR001
     *
     * @mbggenerated
     */
    private String pcr001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.PCR002
     *
     * @mbggenerated
     */
    private String pcr002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.PCR003
     *
     * @mbggenerated
     */
    private String pcr003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.PCR004
     *
     * @mbggenerated
     */
    private String pcr004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.CREATEBY
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.UPDATEDATE
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.UPDATEBY
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.DELETEBY
     *
     * @mbggenerated
     */
    private String deleteby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.DELETEDATE
     *
     * @mbggenerated
     */
    private Date deletedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.PCR005
     *
     * @mbggenerated
     */
    private String pcr005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.PCR006
     *
     * @mbggenerated
     */
    private String pcr006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.PCR007
     *
     * @mbggenerated
     */
    private String pcr007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column POOR_CHANGE_RECORD.PCR008
     *
     * @mbggenerated
     */
    private String pcr008;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.PCR001
     *
     * @return the value of POOR_CHANGE_RECORD.PCR001
     *
     * @mbggenerated
     */
    public String getPcr001() {
        return pcr001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.PCR001
     *
     * @param pcr001 the value for POOR_CHANGE_RECORD.PCR001
     *
     * @mbggenerated
     */
    public void setPcr001(String pcr001) {
        this.pcr001 = pcr001 == null ? null : pcr001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.PCR002
     *
     * @return the value of POOR_CHANGE_RECORD.PCR002
     *
     * @mbggenerated
     */
    public String getPcr002() {
        return pcr002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.PCR002
     *
     * @param pcr002 the value for POOR_CHANGE_RECORD.PCR002
     *
     * @mbggenerated
     */
    public void setPcr002(String pcr002) {
        this.pcr002 = pcr002 == null ? null : pcr002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.PCR003
     *
     * @return the value of POOR_CHANGE_RECORD.PCR003
     *
     * @mbggenerated
     */
    public String getPcr003() {
        return pcr003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.PCR003
     *
     * @param pcr003 the value for POOR_CHANGE_RECORD.PCR003
     *
     * @mbggenerated
     */
    public void setPcr003(String pcr003) {
        this.pcr003 = pcr003 == null ? null : pcr003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.PCR004
     *
     * @return the value of POOR_CHANGE_RECORD.PCR004
     *
     * @mbggenerated
     */
    public String getPcr004() {
        return pcr004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.PCR004
     *
     * @param pcr004 the value for POOR_CHANGE_RECORD.PCR004
     *
     * @mbggenerated
     */
    public void setPcr004(String pcr004) {
        this.pcr004 = pcr004 == null ? null : pcr004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.AAE011
     *
     * @return the value of POOR_CHANGE_RECORD.AAE011
     *
     * @mbggenerated
     */
    public String getAae011() {
        return aae011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.AAE011
     *
     * @param aae011 the value for POOR_CHANGE_RECORD.AAE011
     *
     * @mbggenerated
     */
    public void setAae011(String aae011) {
        this.aae011 = aae011 == null ? null : aae011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.AAE036
     *
     * @return the value of POOR_CHANGE_RECORD.AAE036
     *
     * @mbggenerated
     */
    public Date getAae036() {
        return aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.AAE036
     *
     * @param aae036 the value for POOR_CHANGE_RECORD.AAE036
     *
     * @mbggenerated
     */
    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.CREATEBY
     *
     * @return the value of POOR_CHANGE_RECORD.CREATEBY
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.CREATEBY
     *
     * @param createby the value for POOR_CHANGE_RECORD.CREATEBY
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.UPDATEDATE
     *
     * @return the value of POOR_CHANGE_RECORD.UPDATEDATE
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.UPDATEDATE
     *
     * @param updatedate the value for POOR_CHANGE_RECORD.UPDATEDATE
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.UPDATEBY
     *
     * @return the value of POOR_CHANGE_RECORD.UPDATEBY
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.UPDATEBY
     *
     * @param updateby the value for POOR_CHANGE_RECORD.UPDATEBY
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.DELETEBY
     *
     * @return the value of POOR_CHANGE_RECORD.DELETEBY
     *
     * @mbggenerated
     */
    public String getDeleteby() {
        return deleteby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.DELETEBY
     *
     * @param deleteby the value for POOR_CHANGE_RECORD.DELETEBY
     *
     * @mbggenerated
     */
    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby == null ? null : deleteby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.DELETEDATE
     *
     * @return the value of POOR_CHANGE_RECORD.DELETEDATE
     *
     * @mbggenerated
     */
    public Date getDeletedate() {
        return deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.DELETEDATE
     *
     * @param deletedate the value for POOR_CHANGE_RECORD.DELETEDATE
     *
     * @mbggenerated
     */
    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.PCR005
     *
     * @return the value of POOR_CHANGE_RECORD.PCR005
     *
     * @mbggenerated
     */
    public String getPcr005() {
        return pcr005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.PCR005
     *
     * @param pcr005 the value for POOR_CHANGE_RECORD.PCR005
     *
     * @mbggenerated
     */
    public void setPcr005(String pcr005) {
        this.pcr005 = pcr005 == null ? null : pcr005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.PCR006
     *
     * @return the value of POOR_CHANGE_RECORD.PCR006
     *
     * @mbggenerated
     */
    public String getPcr006() {
        return pcr006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.PCR006
     *
     * @param pcr006 the value for POOR_CHANGE_RECORD.PCR006
     *
     * @mbggenerated
     */
    public void setPcr006(String pcr006) {
        this.pcr006 = pcr006 == null ? null : pcr006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.PCR007
     *
     * @return the value of POOR_CHANGE_RECORD.PCR007
     *
     * @mbggenerated
     */
    public String getPcr007() {
        return pcr007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.PCR007
     *
     * @param pcr007 the value for POOR_CHANGE_RECORD.PCR007
     *
     * @mbggenerated
     */
    public void setPcr007(String pcr007) {
        this.pcr007 = pcr007 == null ? null : pcr007.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POOR_CHANGE_RECORD.PCR008
     *
     * @return the value of POOR_CHANGE_RECORD.PCR008
     *
     * @mbggenerated
     */
    public String getPcr008() {
        return pcr008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POOR_CHANGE_RECORD.PCR008
     *
     * @param pcr008 the value for POOR_CHANGE_RECORD.PCR008
     *
     * @mbggenerated
     */
    public void setPcr008(String pcr008) {
        this.pcr008 = pcr008 == null ? null : pcr008.trim();
    }
}