package com.tdkj.model;

import java.util.Date;

public class PovertyAlleviationBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.PAB001
     *
     * @mbggenerated
     */
    private String pab001;
    private Long pab011;
    private Long pab012;
    private String pab013;
    private String pab014;
    private String rn;
    private String deleteby;

    private Date deletedate;

    private String istaizahang;//判断是不是台账进来查询的，如果则不为空    虚拟字段
    private String taizhang;//判断是不是台账进来查询的，如果则不为空    虚拟字段
    private String pab015;

    private String istobecomplete; //是否待完善列表查询    虚拟字段

    private String pab016;

    private String pab017;

    private String pab018;

    private String pab019;

    private String pab020;

    public String getPab016() {
        return pab016;
    }

    public void setPab016(String pab016) {
        this.pab016 = pab016;
    }

    public String getPab017() {
        return pab017;
    }

    public void setPab017(String pab017) {
        this.pab017 = pab017;
    }

    public String getPab018() {
        return pab018;
    }

    public void setPab018(String pab018) {
        this.pab018 = pab018;
    }

    public String getPab019() {
        return pab019;
    }

    public void setPab019(String pab019) {
        this.pab019 = pab019;
    }

    public String getPab020() {
        return pab020;
    }

    public void setPab020(String pab020) {
        this.pab020 = pab020;
    }

    public String getIstobecomplete() {
        return istobecomplete;
    }

    public void setIstobecomplete(String istobecomplete) {
        this.istobecomplete = istobecomplete;
    }

    public String getPab015() {
        return pab015;
    }

    public void setPab015(String pab015) {
        this.pab015 = pab015;
    }

    public String getTaizhang() {
        return taizhang;
    }

    public void setTaizhang(String taizhang) {
        this.taizhang = taizhang;
    }

    public String getIstaizahang() {
        return istaizahang;
    }

    public void setIstaizahang(String istaizahang) {
        this.istaizahang = istaizahang;
    }

    public String getPab014() {
        return pab014;
    }

    public void setPab014(String pab014) {
        this.pab014 = pab014;
    }

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    public String getRn() {
        return rn;
    }

    public void setRn(String rn) {
        this.rn = rn;
    }

    public String getPab013() {
        return pab013;
    }

    public void setPab013(String pab013) {
        this.pab013 = pab013;
    }

    public Long getPab011() {
        return pab011;
    }

    public void setPab011(Long pab011) {
        this.pab011 = pab011;
    }

    public Long getPab012() {
        return pab012;
    }

    public void setPab012(Long pab012) {
        this.pab012 = pab012;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.AAB301
     *
     * @mbggenerated
     */
    private String aab301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.PAB003
     *
     * @mbggenerated
     */
    private String pab003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.PAB004
     *
     * @mbggenerated
     */
    private String pab004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.PAB007
     *
     * @mbggenerated
     */
    private Integer pab007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.PAB008
     *
     * @mbggenerated
     */
    private Integer pab008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.PAB009
     *
     * @mbggenerated
     */
    private String pab009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.PAB010
     *
     * @mbggenerated
     */
    private String pab010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.PAB006
     *
     * @mbggenerated
     */
    private String pab006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.PAB005
     *
     * @mbggenerated
     */
    private String pab005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poverty_alleviation_base.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae012;

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.PAB001
     *
     * @return the value of poverty_alleviation_base.PAB001
     *
     * @mbggenerated
     */
    public String getPab001() {
        return pab001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.PAB001
     *
     * @param pab001 the value for poverty_alleviation_base.PAB001
     *
     * @mbggenerated
     */
    public void setPab001(String pab001) {
        this.pab001 = pab001 == null ? null : pab001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.AAB301
     *
     * @return the value of poverty_alleviation_base.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.AAB301
     *
     * @param aab301 the value for poverty_alleviation_base.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.PAB003
     *
     * @return the value of poverty_alleviation_base.PAB003
     *
     * @mbggenerated
     */
    public String getPab003() {
        return pab003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.PAB003
     *
     * @param pab003 the value for poverty_alleviation_base.PAB003
     *
     * @mbggenerated
     */
    public void setPab003(String pab003) {
        this.pab003 = pab003 == null ? null : pab003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.PAB004
     *
     * @return the value of poverty_alleviation_base.PAB004
     *
     * @mbggenerated
     */
    public String getPab004() {
        return pab004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.PAB004
     *
     * @param pab004 the value for poverty_alleviation_base.PAB004
     *
     * @mbggenerated
     */
    public void setPab004(String pab004) {
        this.pab004 = pab004 == null ? null : pab004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.PAB007
     *
     * @return the value of poverty_alleviation_base.PAB007
     *
     * @mbggenerated
     */
    public Integer getPab007() {
        return pab007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.PAB007
     *
     * @param pab007 the value for poverty_alleviation_base.PAB007
     *
     * @mbggenerated
     */
    public void setPab007(Integer pab007) {
        this.pab007 = pab007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.PAB008
     *
     * @return the value of poverty_alleviation_base.PAB008
     *
     * @mbggenerated
     */
    public Integer getPab008() {
        return pab008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.PAB008
     *
     * @param pab008 the value for poverty_alleviation_base.PAB008
     *
     * @mbggenerated
     */
    public void setPab008(Integer pab008) {
        this.pab008 = pab008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.PAB009
     *
     * @return the value of poverty_alleviation_base.PAB009
     *
     * @mbggenerated
     */
    public String getPab009() {
        return pab009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.PAB009
     *
     * @param pab009 the value for poverty_alleviation_base.PAB009
     *
     * @mbggenerated
     */
    public void setPab009(String pab009) {
        this.pab009 = pab009 == null ? null : pab009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.PAB010
     *
     * @return the value of poverty_alleviation_base.PAB010
     *
     * @mbggenerated
     */
    public String getPab010() {
        return pab010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.PAB010
     *
     * @param pab010 the value for poverty_alleviation_base.PAB010
     *
     * @mbggenerated
     */
    public void setPab010(String pab010) {
        this.pab010 = pab010 == null ? null : pab010.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.PAB006
     *
     * @return the value of poverty_alleviation_base.PAB006
     *
     * @mbggenerated
     */
    public String getPab006() {
        return pab006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.PAB006
     *
     * @param pab006 the value for poverty_alleviation_base.PAB006
     *
     * @mbggenerated
     */
    public void setPab006(String pab006) {
        this.pab006 = pab006 == null ? null : pab006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.PAB005
     *
     * @return the value of poverty_alleviation_base.PAB005
     *
     * @mbggenerated
     */
    public String getPab005() {
        return pab005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.PAB005
     *
     * @param pab005 the value for poverty_alleviation_base.PAB005
     *
     * @mbggenerated
     */
    public void setPab005(String pab005) {
        this.pab005 = pab005 == null ? null : pab005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.AAE036
     *
     * @return the value of poverty_alleviation_base.AAE036
     *
     * @mbggenerated
     */
    public Date getAae036() {
        return aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.AAE036
     *
     * @param aae036 the value for poverty_alleviation_base.AAE036
     *
     * @mbggenerated
     */
    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poverty_alleviation_base.AAE011
     *
     * @return the value of poverty_alleviation_base.AAE011
     *
     * @mbggenerated
     */
    public String getAae011() {
        return aae011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poverty_alleviation_base.AAE011
     *
     * @param aae011 the value for poverty_alleviation_base.AAE011
     *
     * @mbggenerated
     */
    public void setAae011(String aae011) {
        this.aae011 = aae011 == null ? null : aae011.trim();
    }
}