package com.tdkj.model;

import java.util.Date;

public class TechnicalSchools {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS001
     *
     * @mbggenerated
     */
    private String ths001;
    private String ths013;
    private String ths014;
    private String ths015;
    private String ths016;
    private String isnew;
    private String deleteby;

    private Date deletedate;

    private String phd013;
    private String phd014;
    private String plf004;
    private String plf005;

    public String getPhd013() {
        return phd013;
    }

    public void setPhd013(String phd013) {
        this.phd013 = phd013;
    }

    public String getPhd014() {
        return phd014;
    }

    public void setPhd014(String phd014) {
        this.phd014 = phd014;
    }

    public String getPlf004() {
        return plf004;
    }

    public void setPlf004(String plf004) {
        this.plf004 = plf004;
    }

    public String getPlf005() {
        return plf005;
    }

    public void setPlf005(String plf005) {
        this.plf005 = plf005;
    }

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    public String getIsnew() {
        return isnew;
    }

    public void setIsnew(String isnew) {
        this.isnew = isnew;
    }

    public String getThs016() {
        return ths016;
    }

    public void setThs016(String ths016) {
        this.ths016 = ths016;
    }

    public String getThs013() {
        return ths013;
    }

    public void setThs013(String ths013) {
        this.ths013 = ths013;
    }

    public String getThs014() {
        return ths014;
    }

    public void setThs014(String ths014) {
        this.ths014 = ths014;
    }

    public String getThs015() {
        return ths015;
    }

    public void setThs015(String ths015) {
        this.ths015 = ths015;
    }



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.AAB301
     *
     * @mbggenerated
     */
    private String aab301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS003
     *
     * @mbggenerated
     */
    private String ths003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS004
     *
     * @mbggenerated
     */
    private String ths004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS005
     *
     * @mbggenerated
     */
    private String ths005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS006
     *
     * @mbggenerated
     */
    private String ths006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS007
     *
     * @mbggenerated
     */
    private String ths007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS008
     *
     * @mbggenerated
     */
    private String ths008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS009
     *
     * @mbggenerated
     */
    private String ths009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS010
     *
     * @mbggenerated
     */
    private String ths010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS011
     *
     * @mbggenerated
     */
    private String ths011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS012
     *
     * @mbggenerated
     */
    private String ths012;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS002
     *
     * @mbggenerated
     */
    private String ths002;

    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae012;

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS001
     *
     * @return the value of technical_schools.THS001
     *
     * @mbggenerated
     */
    public String getThs001() {
        return ths001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS001
     *
     * @param ths001 the value for technical_schools.THS001
     *
     * @mbggenerated
     */
    public void setThs001(String ths001) {
        this.ths001 = ths001 == null ? null : ths001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.AAB301
     *
     * @return the value of technical_schools.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.AAB301
     *
     * @param aab301 the value for technical_schools.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS003
     *
     * @return the value of technical_schools.THS003
     *
     * @mbggenerated
     */
    public String getThs003() {
        return ths003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS003
     *
     * @param ths003 the value for technical_schools.THS003
     *
     * @mbggenerated
     */
    public void setThs003(String ths003) {
        this.ths003 = ths003 == null ? null : ths003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS004
     *
     * @return the value of technical_schools.THS004
     *
     * @mbggenerated
     */
    public String getThs004() {
        return ths004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS004
     *
     * @param ths004 the value for technical_schools.THS004
     *
     * @mbggenerated
     */
    public void setThs004(String ths004) {
        this.ths004 = ths004 == null ? null : ths004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS005
     *
     * @return the value of technical_schools.THS005
     *
     * @mbggenerated
     */
    public String getThs005() {
        return ths005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS005
     *
     * @param ths005 the value for technical_schools.THS005
     *
     * @mbggenerated
     */
    public void setThs005(String ths005) {
        this.ths005 = ths005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS006
     *
     * @return the value of technical_schools.THS006
     *
     * @mbggenerated
     */
    public String getThs006() {
        return ths006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS006
     *
     * @param ths006 the value for technical_schools.THS006
     *
     * @mbggenerated
     */
    public void setThs006(String ths006) {
        this.ths006 = ths006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS007
     *
     * @return the value of technical_schools.THS007
     *
     * @mbggenerated
     */
    public String getThs007() {
        return ths007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS007
     *
     * @param ths007 the value for technical_schools.THS007
     *
     * @mbggenerated
     */
    public void setThs007(String ths007) {
        this.ths007 = ths007 == null ? null : ths007.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS008
     *
     * @return the value of technical_schools.THS008
     *
     * @mbggenerated
     */
    public String getThs008() {
        return ths008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS008
     *
     * @param ths008 the value for technical_schools.THS008
     *
     * @mbggenerated
     */
    public void setThs008(String ths008) {
        this.ths008 = ths008 == null ? null : ths008.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS009
     *
     * @return the value of technical_schools.THS009
     *
     * @mbggenerated
     */
    public String getThs009() {
        return ths009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS009
     *
     * @param ths009 the value for technical_schools.THS009
     *
     * @mbggenerated
     */
    public void setThs009(String ths009) {
        this.ths009 = ths009 == null ? null : ths009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS010
     *
     * @return the value of technical_schools.THS010
     *
     * @mbggenerated
     */
    public String getThs010() {
        return ths010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS010
     *
     * @param ths010 the value for technical_schools.THS010
     *
     * @mbggenerated
     */
    public void setThs010(String ths010) {
        this.ths010 = ths010 == null ? null : ths010.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS011
     *
     * @return the value of technical_schools.THS011
     *
     * @mbggenerated
     */
    public String getThs011() {
        return ths011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS011
     *
     * @param ths011 the value for technical_schools.THS011
     *
     * @mbggenerated
     */
    public void setThs011(String ths011) {
        this.ths011 = ths011 == null ? null : ths011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS012
     *
     * @return the value of technical_schools.THS012
     *
     * @mbggenerated
     */
    public String getThs012() {
        return ths012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS012
     *
     * @param ths012 the value for technical_schools.THS012
     *
     * @mbggenerated
     */
    public void setThs012(String ths012) {
        this.ths012 = ths012 == null ? null : ths012.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.AAE036
     *
     * @return the value of technical_schools.AAE036
     *
     * @mbggenerated
     */
    public Date getAae036() {
        return aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.AAE036
     *
     * @param aae036 the value for technical_schools.AAE036
     *
     * @mbggenerated
     */
    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.AAE011
     *
     * @return the value of technical_schools.AAE011
     *
     * @mbggenerated
     */
    public String getAae011() {
        return aae011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.AAE011
     *
     * @param aae011 the value for technical_schools.AAE011
     *
     * @mbggenerated
     */
    public void setAae011(String aae011) {
        this.aae011 = aae011 == null ? null : aae011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technical_schools.THS002
     *
     * @return the value of technical_schools.THS002
     *
     * @mbggenerated
     */
    public String getThs002() {
        return ths002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technical_schools.THS002
     *
     * @param ths002 the value for technical_schools.THS002
     *
     * @mbggenerated
     */
    public void setThs002(String ths002) {
        this.ths002 = ths002 == null ? null : ths002.trim();
    }
}