package com.tdkj.model;

import java.util.Date;

/**
 * Created by len on 2019-06-02.
 * 虚拟实体
 */
public class ThsPlf {

    private String ths001;
    private String ths013;
    private String ths014;
    private String ths015;
    private String ths016;
    private String aab301;

    private String phd013;//异地搬迁
    private String phd007;//家庭住址
    private String rn;
    private String isnew;
    private String deleteby;

    private Date deletedate;

    private String helpyear;//帮扶年度  虚拟字段

    private String isnoduty;//是否在岗  虚拟字段

    private String phd014;//脱贫状态

    private String showscope;//显示范围    1 默认显示符合条件的劳动力    空  显示全部

    private String istobecomplete;  //虚拟字段  是否待完善

    private String phd014_19;//是否是2019年认定的贫困户

    public String getPhd014_19() {
        return phd014_19;
    }

    public void setPhd014_19(String phd014_19) {
        this.phd014_19 = phd014_19;
    }

    public String getIstobecomplete() {
        return istobecomplete;
    }

    public void setIstobecomplete(String istobecomplete) {
        this.istobecomplete = istobecomplete;
    }

    public String getShowscope() {
        return showscope;
    }

    public void setShowscope(String showscope) {
        this.showscope = showscope;
    }

    public String getPhd014() {
        return phd014;
    }

    public void setPhd014(String phd014) {
        this.phd014 = phd014;
    }


    public String getIsnoduty() {
        return isnoduty;
    }

    public void setIsnoduty(String isnoduty) {
        this.isnoduty = isnoduty;
    }

    public String getHelpyear() {
        return helpyear;
    }

    public void setHelpyear(String helpyear) {
        this.helpyear = helpyear;
    }

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }



    public String getIsnew() {
        return isnew;
    }

    public void setIsnew(String isnew) {
        this.isnew = isnew;
    }

    public String getPhd013() {
        return phd013;
    }

    public void setPhd013(String phd013) {
        this.phd013 = phd013;
    }

    public String getPhd007() {
        return phd007;
    }

    public void setPhd007(String phd007) {
        this.phd007 = phd007;
    }

    public String getRn() {
        return rn;
    }

    public void setRn(String rn) {
        this.rn = rn;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS003
     *
     * @mbggenerated
     */
    private String ths003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS004
     *
     * @mbggenerated
     */
    private String ths004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS005
     *
     * @mbggenerated
     */
    private String ths005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS006
     *
     * @mbggenerated
     */
    private String ths006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS007
     *
     * @mbggenerated
     */
    private String ths007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS008
     *
     * @mbggenerated
     */
    private String ths008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS009
     *
     * @mbggenerated
     */
    private String ths009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS010
     *
     * @mbggenerated
     */
    private String ths010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS011
     *
     * @mbggenerated
     */
    private String ths011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS012
     *
     * @mbggenerated
     */
    private String ths012;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technical_schools.THS002
     *
     * @mbggenerated
     */
    private String ths002;

    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae012;

    private String plf004;

    private String plf005;

    private String plf006;

    private String plf007;

    private String plf008;

    private String plf009;

    private String plf010;

    private String plf011;

    private String plf012;

    private String plf013;

    private String plf014;

    private String plf016;

    private String plf015;

    private String plf017;

    private String plf018;

    private String plf019;

    private String plf020;

    private String plf021;

    private String plf022;

    private String plf023;
    private String plf024;

    private String plf001;

    private String plf002;

    private String startage;    //年龄开始  虚拟字段
    private String endage;//年龄结束  虚拟字段

    public String getStartage() {
        return startage;
    }

    public void setStartage(String startage) {
        this.startage = startage;
    }

    public String getEndage() {
        return endage;
    }

    public String getPlf001() {
        return plf001;
    }

    public void setPlf001(String plf001) {
        this.plf001 = plf001;
    }

    public String getPlf002() {
        return plf002;
    }

    public void setPlf002(String plf002) {
        this.plf002 = plf002;
    }

    public String getThs001() {
        return ths001;
    }

    public void setThs001(String ths001) {
        this.ths001 = ths001;
    }

    public String getThs013() {
        return ths013;
    }

    public void setThs013(String ths013) {
        this.ths013 = ths013;
    }

    public String getThs014() {
        return ths014;
    }

    public void setThs014(String ths014) {
        this.ths014 = ths014;
    }

    public String getThs015() {
        return ths015;
    }

    public void setThs015(String ths015) {
        this.ths015 = ths015;
    }

    public String getThs016() {
        return ths016;
    }

    public void setThs016(String ths016) {
        this.ths016 = ths016;
    }

    public String getAab301() {
        return aab301;
    }

    public void setAab301(String aab301) {
        this.aab301 = aab301;
    }

    public String getThs003() {
        return ths003;
    }

    public void setThs003(String ths003) {
        this.ths003 = ths003;
    }

    public String getThs004() {
        return ths004;
    }

    public void setThs004(String ths004) {
        this.ths004 = ths004;
    }

    public String getThs005() {
        return ths005;
    }

    public void setThs005(String ths005) {
        this.ths005 = ths005;
    }

    public String getThs006() {
        return ths006;
    }

    public void setThs006(String ths006) {
        this.ths006 = ths006;
    }

    public String getThs007() {
        return ths007;
    }

    public void setThs007(String ths007) {
        this.ths007 = ths007;
    }

    public String getThs008() {
        return ths008;
    }

    public void setThs008(String ths008) {
        this.ths008 = ths008;
    }

    public String getThs009() {
        return ths009;
    }

    public void setThs009(String ths009) {
        this.ths009 = ths009;
    }

    public String getThs010() {
        return ths010;
    }

    public void setThs010(String ths010) {
        this.ths010 = ths010;
    }

    public String getThs011() {
        return ths011;
    }

    public void setThs011(String ths011) {
        this.ths011 = ths011;
    }

    public String getThs012() {
        return ths012;
    }

    public void setThs012(String ths012) {
        this.ths012 = ths012;
    }

    public Date getAae036() {
        return aae036;
    }

    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }

    public String getAae011() {
        return aae011;
    }

    public void setAae011(String aae011) {
        this.aae011 = aae011;
    }

    public String getThs002() {
        return ths002;
    }

    public void setThs002(String ths002) {
        this.ths002 = ths002;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getPlf004() {
        return plf004;
    }

    public void setPlf004(String plf004) {
        this.plf004 = plf004;
    }

    public String getPlf005() {
        return plf005;
    }

    public void setPlf005(String plf005) {
        this.plf005 = plf005;
    }

    public String getPlf006() {
        return plf006;
    }

    public void setPlf006(String plf006) {
        this.plf006 = plf006;
    }

    public String getPlf007() {
        return plf007;
    }

    public void setPlf007(String plf007) {
        this.plf007 = plf007;
    }

    public String getPlf008() {
        return plf008;
    }

    public void setPlf008(String plf008) {
        this.plf008 = plf008;
    }

    public String getPlf009() {
        return plf009;
    }

    public void setPlf009(String plf009) {
        this.plf009 = plf009;
    }

    public String getPlf010() {
        return plf010;
    }

    public void setPlf010(String plf010) {
        this.plf010 = plf010;
    }

    public String getPlf011() {
        return plf011;
    }

    public void setPlf011(String plf011) {
        this.plf011 = plf011;
    }

    public String getPlf012() {
        return plf012;
    }

    public void setPlf012(String plf012) {
        this.plf012 = plf012;
    }

    public String getPlf013() {
        return plf013;
    }

    public void setPlf013(String plf013) {
        this.plf013 = plf013;
    }

    public String getPlf014() {
        return plf014;
    }

    public void setPlf014(String plf014) {
        this.plf014 = plf014;
    }

    public String getPlf016() {
        return plf016;
    }

    public void setPlf016(String plf016) {
        this.plf016 = plf016;
    }

    public String getPlf015() {
        return plf015;
    }

    public void setPlf015(String plf015) {
        this.plf015 = plf015;
    }

    public String getPlf017() {
        return plf017;
    }

    public void setPlf017(String plf017) {
        this.plf017 = plf017;
    }

    public String getPlf018() {
        return plf018;
    }

    public void setPlf018(String plf018) {
        this.plf018 = plf018;
    }

    public String getPlf019() {
        return plf019;
    }

    public void setPlf019(String plf019) {
        this.plf019 = plf019;
    }

    public String getPlf020() {
        return plf020;
    }

    public void setPlf020(String plf020) {
        this.plf020 = plf020;
    }

    public String getPlf021() {
        return plf021;
    }

    public void setPlf021(String plf021) {
        this.plf021 = plf021;
    }

    public String getPlf022() {
        return plf022;
    }

    public void setPlf022(String plf022) {
        this.plf022 = plf022;
    }

    public String getPlf023() {
        return plf023;
    }

    public void setPlf023(String plf023) {
        this.plf023 = plf023;
    }

    public String getPlf024() {
        return plf024;
    }

    public void setPlf024(String plf024) {
        this.plf024 = plf024;
    }
}
