package com.tdkj.model;

import java.util.Date;

public class TrainingSituation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN001
     *
     * @mbggenerated
     */
    private String tsn001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN010
     *
     * @mbggenerated
     */
    private String tsn010;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN003
     *
     * @mbggenerated
     */
    private String tsn003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN004
     *
     * @mbggenerated
     */
    private String tsn004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN005
     *
     * @mbggenerated
     */
    private String tsn005;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN006
     *
     * @mbggenerated
     */
    private String tsn006;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN007
     *
     * @mbggenerated
     */
    private String tsn007;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN008
     *
     * @mbggenerated
     */
    private String tsn008;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN002
     *
     * @mbggenerated
     */
    private String tsn002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN009
     *
     * @mbggenerated
     */
    private String tsn009;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.AAB301
     *
     * @mbggenerated
     */
    private String aab301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.AAE036
     *
     * @mbggenerated
     */
    private Date aae036;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.AAE011
     *
     * @mbggenerated
     */
    private String aae011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column training_situation.TSN011
     *
     * @mbggenerated
     */
    private String tsn011;

    private String datasource;

    private String aae100;

    private Date updatedate;

    private String updateby;

    private String createby;

    private String aae012;

    private String tsn012;
    private String tsn013;
    private String tsn014;
    private String tsn015;
    private String tsn016;
    private String isnew;
    private String deleteby;

    private Date deletedate;

    private String phd013;
    private String phd014;
    private String plf004;
    private String plf005;

    public String getPhd013() {
        return phd013;
    }

    public void setPhd013(String phd013) {
        this.phd013 = phd013;
    }

    public String getPhd014() {
        return phd014;
    }

    public void setPhd014(String phd014) {
        this.phd014 = phd014;
    }

    public String getPlf004() {
        return plf004;
    }

    public void setPlf004(String plf004) {
        this.plf004 = plf004;
    }

    public String getPlf005() {
        return plf005;
    }

    public void setPlf005(String plf005) {
        this.plf005 = plf005;
    }

    public String getDeleteby() {
        return deleteby;
    }

    public void setDeleteby(String deleteby) {
        this.deleteby = deleteby;
    }

    public Date getDeletedate() {
        return deletedate;
    }

    public void setDeletedate(Date deletedate) {
        this.deletedate = deletedate;
    }

    public String getIsnew() {
        return isnew;
    }

    public void setIsnew(String isnew) {
        this.isnew = isnew;
    }

    public String getTsn012() {
        return tsn012;
    }

    public void setTsn012(String tsn012) {
        this.tsn012 = tsn012;
    }

    public String getTsn013() {
        return tsn013;
    }

    public void setTsn013(String tsn013) {
        this.tsn013 = tsn013;
    }

    public String getTsn014() {
        return tsn014;
    }

    public void setTsn014(String tsn014) {
        this.tsn014 = tsn014;
    }

    public String getTsn015() {
        return tsn015;
    }

    public void setTsn015(String tsn015) {
        this.tsn015 = tsn015;
    }

    public String getTsn016() {
        return tsn016;
    }

    public void setTsn016(String tsn016) {
        this.tsn016 = tsn016;
    }

    public String getAae100() {
        return aae100;
    }

    public void setAae100(String aae100) {
        this.aae100 = aae100;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public String getAae012() {
        return aae012;
    }

    public void setAae012(String aae012) {
        this.aae012 = aae012;
    }

    public String getDatasource() {
        return datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN001
     *
     * @return the value of training_situation.TSN001
     *
     * @mbggenerated
     */
    public String getTsn001() {
        return tsn001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN001
     *
     * @param tsn001 the value for training_situation.TSN001
     *
     * @mbggenerated
     */
    public void setTsn001(String tsn001) {
        this.tsn001 = tsn001 == null ? null : tsn001.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN010
     *
     * @return the value of training_situation.TSN010
     *
     * @mbggenerated
     */
    public String getTsn010() {
        return tsn010;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN010
     *
     * @param tsn010 the value for training_situation.TSN010
     *
     * @mbggenerated
     */
    public void setTsn010(String tsn010) {
        this.tsn010 = tsn010 == null ? null : tsn010.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN003
     *
     * @return the value of training_situation.TSN003
     *
     * @mbggenerated
     */
    public String getTsn003() {
        return tsn003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN003
     *
     * @param tsn003 the value for training_situation.TSN003
     *
     * @mbggenerated
     */
    public void setTsn003(String tsn003) {
        this.tsn003 = tsn003 == null ? null : tsn003.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN004
     *
     * @return the value of training_situation.TSN004
     *
     * @mbggenerated
     */
    public String getTsn004() {
        return tsn004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN004
     *
     * @param tsn004 the value for training_situation.TSN004
     *
     * @mbggenerated
     */
    public void setTsn004(String tsn004) {
        this.tsn004 = tsn004 == null ? null : tsn004.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN005
     *
     * @return the value of training_situation.TSN005
     *
     * @mbggenerated
     */
    public String getTsn005() {
        return tsn005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN005
     *
     * @param tsn005 the value for training_situation.TSN005
     *
     * @mbggenerated
     */
    public void setTsn005(String tsn005) {
        this.tsn005 = tsn005 == null ? null : tsn005.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN006
     *
     * @return the value of training_situation.TSN006
     *
     * @mbggenerated
     */
    public String getTsn006() {
        return tsn006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN006
     *
     * @param tsn006 the value for training_situation.TSN006
     *
     * @mbggenerated
     */
    public void setTsn006(String tsn006) {
        this.tsn006 = tsn006 == null ? null : tsn006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN007
     *
     * @return the value of training_situation.TSN007
     *
     * @mbggenerated
     */
    public String getTsn007() {
        return tsn007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN007
     *
     * @param tsn007 the value for training_situation.TSN007
     *
     * @mbggenerated
     */
    public void setTsn007(String tsn007) {
        this.tsn007 = tsn007;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN008
     *
     * @return the value of training_situation.TSN008
     *
     * @mbggenerated
     */
    public String getTsn008() {
        return tsn008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN008
     *
     * @param tsn008 the value for training_situation.TSN008
     *
     * @mbggenerated
     */
    public void setTsn008(String tsn008) {
        this.tsn008 = tsn008;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN002
     *
     * @return the value of training_situation.TSN002
     *
     * @mbggenerated
     */
    public String getTsn002() {
        return tsn002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN002
     *
     * @param tsn002 the value for training_situation.TSN002
     *
     * @mbggenerated
     */
    public void setTsn002(String tsn002) {
        this.tsn002 = tsn002 == null ? null : tsn002.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN009
     *
     * @return the value of training_situation.TSN009
     *
     * @mbggenerated
     */
    public String getTsn009() {
        return tsn009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN009
     *
     * @param tsn009 the value for training_situation.TSN009
     *
     * @mbggenerated
     */
    public void setTsn009(String tsn009) {
        this.tsn009 = tsn009 == null ? null : tsn009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.AAB301
     *
     * @return the value of training_situation.AAB301
     *
     * @mbggenerated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.AAB301
     *
     * @param aab301 the value for training_situation.AAB301
     *
     * @mbggenerated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.AAE036
     *
     * @return the value of training_situation.AAE036
     *
     * @mbggenerated
     */
    public Date getAae036() {
        return aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.AAE036
     *
     * @param aae036 the value for training_situation.AAE036
     *
     * @mbggenerated
     */
    public void setAae036(Date aae036) {
        this.aae036 = aae036;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.AAE011
     *
     * @return the value of training_situation.AAE011
     *
     * @mbggenerated
     */
    public String getAae011() {
        return aae011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.AAE011
     *
     * @param aae011 the value for training_situation.AAE011
     *
     * @mbggenerated
     */
    public void setAae011(String aae011) {
        this.aae011 = aae011 == null ? null : aae011.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column training_situation.TSN011
     *
     * @return the value of training_situation.TSN011
     *
     * @mbggenerated
     */
    public String getTsn011() {
        return tsn011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column training_situation.TSN011
     *
     * @param tsn011 the value for training_situation.TSN011
     *
     * @mbggenerated
     */
    public void setTsn011(String tsn011) {
        this.tsn011 = tsn011 == null ? null : tsn011.trim();
    }
}