package com.tdkj.dao.InformationCollection;

import com.tdkj.model.EmploymentSituation;
import com.tdkj.model.Entrepreneurship;
import com.tdkj.model.EysPlf;
import com.tdkj.model.PoorLaborForce;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface EmploymentSituationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String eys001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    int insert(EmploymentSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    int insertSelective(EmploymentSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    EmploymentSituation selectByPrimaryKey(String eys001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmploymentSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmploymentSituation record);

    /**
     * 根据劳动力id  查询该劳动力的就业技能
     * @return
     */
    public List<EmploymentSituation> queryEmploymentSituationByEys002(String eys002);

    /**
     * 根据劳动力id  查询该劳动力的公益性岗位
     * @return
     */
    public List<EmploymentSituation> queryEmploymentSituationByEys002Post(String eys002);



    /**
     * 根据劳动力id  删除该劳动力下的所有就业技能情况
     * @return
     */
    public int deleteEmploymentSituationByEys002(@Param("eys002")String eys002,@Param("realname")String realname);

    /**
     * 删除所有公益性岗位有关的就业信息
     * @param eys002
     * @param realname
     * @return
     */
    public int deletePublicPostByEys002(@Param("eys002")String eys002,@Param("realname")String realname);

    /**
     * 根据行政区划查询劳动力就业台账信息
     * @return
     */
    public List<EysPlf> queryEmploymentSituationAccountByAab301(@Param("eysPlf")EysPlf eysPlf, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize);


    /**
     *根据行政区划查询劳动力就业台账总共多条
     * @return
     */
    public String queryAllEmploymentSituationByAab301(@Param("eysPlf")EysPlf eysPlf);


    /**
     * 根据行政区划查询劳动力公益性岗位台账信息
     * @return
     */
    public List<EysPlf> queryPublicPostAccountByAab301(@Param("eysPlf")EysPlf eysPlf, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize);


    /**
     *根据行政区划查询劳动力公益性岗位台账总共多条
     * @return
     */
    public String queryPublicPostCountByAab301(@Param("eysPlf")EysPlf eysPlf);





    /**
     *根据区划查询导出数据
     * @return
     */
    @Select(" select count(1)" +
            "    from recursion r,employment_situation es left join poor_labor_force plf on es.eys002 = plf.plf001" +
            "     where r.aab301=es.aab301 and  es.aae100='1' AND r.parentid=#{aab301}")
    public String queryAllEmploymentSituationByAab301Import(@Param("aab301")String aab301);


    /**
     * 根据劳动力Id 修改isnew=0
     * @param eys002
     * @return
     */
    public int updateIsNewByEys002(@Param("eys002")String eys002);

    /**
     * 批量添加
     * @param list
     * @return
     */
    int addList(@Param("list") List<PoorLaborForce> list);

    //根据劳动力id 查询最新的就业信息
    public EmploymentSituation queryNewEmploymentSituation(@Param("eys002")String eys002);

    /**
     * 实时计算就创业情况
     *
     * @param plf001
     * @return
     */
    @Update(" call P_jy_cy(#{plf001})")
    int f_jy_cy(String plf001);


    /**
     * 根据行政区划查询查询劳动力就业培训列表
     * @return
     */
    List<EysPlf> queryEmploymentSituationTrainingByAab301(@Param("eysPlf")EysPlf eysPlf, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize);


    /**
     *根据行政区划查询劳动力查询劳动力就业培训列表
     * @return
     */
    String queryAllEmploymentSituationTrainingByAab301(@Param("eysPlf")EysPlf eysPlf);




/******************************以下是有问题就业信息查询 ************************************************************************************************************/

    /**
     * 根据行政区划查询劳动力就业台账信息  (有问题数据)
     * @return
     */
    List<EysPlf> queryErrorEmploymentSituationAccountByAab301(@Param("eysPlf")EysPlf eysPlf, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize);


    /**
     *根据行政区划查询劳动力就业台账总共多条  (有问题数据)
     * @return
     */
    String queryAllErrorEmploymentSituationByAab301(@Param("eysPlf")EysPlf eysPlf);


    //************************************以下是弱劳动力就业台账信息**********************************************************************


    /**
     * 根据行政区划查询弱劳动力就业台账信息
     * @param aab301
     * @return
     */
    List<EysPlf> queryRuoEmploymentSituationAccountByAab301(@Param("eysPlf")EysPlf eysPlf, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize);


    /**
     *根据行政区划查询弱劳动力就业台账总共多条
     * @return
     */
    String queryAllRuoEmploymentSituationByAab301(@Param("eysPlf")EysPlf eysPlf);


}