package com.tdkj.dao.InformationCollection;

import com.tdkj.model.Entrepreneurship;
import com.tdkj.model.EppPlf;
import com.tdkj.model.PoorLaborForce;
import com.tdkj.model.TechnicalSchools;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface EntrepreneurshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String epp001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    int insert(Entrepreneurship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    int insertSelective(Entrepreneurship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    Entrepreneurship selectByPrimaryKey(String epp001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Entrepreneurship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Entrepreneurship record);

    /**
     * 根据劳动力主键查询创业信息
     * @param epp002
     * @return
     */
    public List<Entrepreneurship> queryEntrepreneurshipByEpp002(String epp002);


    /**
     * 根据劳动力主键删除创业信息
     * @param epp002
     * @return
     */
    public int deleteEntrepreneurshipByEpp002(@Param("epp002")String epp002,@Param("realname")String realname);


    //************************************以下是台账信息**********************************************************************


    /**
     * 根据行政区划查询劳动力创业台账信息
     * @return
     */
    public List<EppPlf> queryEmploymentShipAccountByAab301(@Param("eppPlf")EppPlf eppPlf, @Param("startRecord")String startRecord,@Param("pageSize") String pageSize);


    /**
     *根据行政区划查询劳动力创业台账总共多条
     * @return
     */
    public String queryAllEmploymentShipByAab301(@Param("eppPlf")EppPlf eppPlf);


    /**
     * 根据劳动力Id 修改isnew=0
     * @param epp002
     * @return
     */
    public int updateIsNewByEpp002(@Param("epp002")String epp002);

    /**
     * 批量添加
     * @param list
     * @return
     */
    int addList(@Param("list") List<PoorLaborForce> list);

    //根据劳动力id 查询最新的创业信息
    public Entrepreneurship queryNewEntrepreneurship(@Param("epp002")String epp002);

    /**
     * 实时计算就创业情况
     *
     * @param plf001
     * @return
     */
    @Update(" call P_jy_cy(#{plf001})")
    int f_jy_cy(String plf001);
}