package com.tdkj.dao.InformationCollection;

import com.tdkj.model.PoorHouseholds;
import com.tdkj.model.PoorHouseholdsTmp;
import com.tdkj.model.PoorLaborForceTmp;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface PoorHouseholdsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poor_households
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String phd001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poor_households
     *
     * @mbggenerated
     */
    int insert(PoorHouseholds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poor_households
     *
     * @mbggenerated
     */
    int insertSelective(PoorHouseholds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poor_households
     *
     * @mbggenerated
     */
    PoorHouseholds selectByPrimaryKey(String phd001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poor_households
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PoorHouseholds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poor_households
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PoorHouseholds record);


    /* 根据行政区划查询贫困户信息
     * @param aab301
     * @return
             */
    public List<PoorHouseholds> queryAllPoorWorkByAab301(@Param("poorHouseholds")PoorHouseholds poorHouseholds, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize);

    /**
     * 根据行政区划查询总共多条
     * @param aab301
     * @return
     */
    public String queryAllByAab301(@Param("poorHouseholds")PoorHouseholds poorHouseholds);


    /**
     * 根据身份证号码查询，该用户是否已经登记
     * @param phd003
     * @return
     */
    public String queryPoorByIdCard(@Param("phd003")String phd003);



    //************************************以下是台账信息**********************************************************************


    /**
     * 根据行政区划查询贫困户台账信息
     * @return
     */
    public List<PoorHouseholds> queryPoorAccountByAab301(@Param("poorHouseholds")PoorHouseholds poorHouseholds,@Param("startRecord")String startRecord,@Param("pageSize")String pageSize);

    /**
     * 根据行政区划查询贫困户台账信息
     * @param aab301
     * @return
     */
    public List<PoorHouseholds> queryPoi(@Param("aab301")String aab301);


    /**
     *根据行政区划查询台账总共多条
     * @return
     */
    public String queryAllAccoutByAab301(@Param("poorHouseholds")PoorHouseholds poorHouseholds);

    /**
     * 根据身份证号码查询家庭户
     * @param phd003
     * @return
     */
    PoorHouseholds selectByPrimaryidCard(@Param("phd003")String phd003);

    /**
     *批量查询
     */
    List<PoorHouseholds> selectByPrimaryidCardList(@Param("selectList")List<String> selectList);

    /**
     *批量修改
     */
    int updateCardList(@Param("updatelist")List<PoorHouseholdsTmp> updatelist);

    /**
     *批量修改劳动力数量
     */
    int updatePhd008(@Param("updatelist")List<PoorHouseholds> updatelist);

    /**
     * 批量添加
     * @param list
     * @return
     */
    int addList(@Param("list") List<PoorHouseholds> list);


    /**
     * 根据行政区划查询待确认贫困户信息
     * @return
     */
    public List<PoorHouseholds> queryToBeComfirePoorByAab301(@Param("poorHouseholds")PoorHouseholds poorHouseholds,@Param("startRecord")String startRecord,@Param("pageSize")String pageSize);


    /**
     *根据行政区划查询待确认贫困户总共多条
     * @return
     */
    public String queryAllToBeComfireByAab301(@Param("poorHouseholds")PoorHouseholds poorHouseholds);


    /**
     * 根据行政区划查询待完善贫困户信息
     * @return
     */
    public List<PoorHouseholds> queryToBeCompletePoorByAab301(@Param("poorHouseholds")PoorHouseholds poorHouseholds,@Param("startRecord")String startRecord,@Param("pageSize")String pageSize);


    /**
     *根据行政区划查询待完善贫困户总共多条
     * @return
     */
    public String queryAllToBeCompleteByAab301(@Param("poorHouseholds")PoorHouseholds poorHouseholds);

    /**
     * 实时更新贫困户劳动力数量
     *
     * @return
     */
    @Update(" call P_phd008(#{phd001})")
    int F_phd008(String phd001);


    //根据劳动力id   修改帮扶措施中的 脱贫状态和易地扶贫
    @Update(" call updateEysEppTsnThsByPlf001(#{phd001})")
    int updateEysEppTsnThsByPlf001(String phd001);


    //************************************以下是  待帮扶   信息**********************************************************************


    /**
     * 根据行政区划查询   待帮扶贫困户 信息
     * @return
     */
    List<PoorHouseholds> queryTobeHelpPoorByAab301(@Param("poorHouseholds")PoorHouseholds poorHouseholds,@Param("startRecord")String startRecord,@Param("pageSize")String pageSize);


    /**
     *根据行政区划查询  待帮扶贫困户  总共多条
     * @return
     */
    String queryAllTobeHelpPoorByAab301(@Param("poorHouseholds")PoorHouseholds poorHouseholds);


}