package com.tdkj.dao.InformationCollection;

import com.tdkj.model.PoorChangeRecord;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PoorChangeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POOR_CHANGE_RECORD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String pcr001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POOR_CHANGE_RECORD
     *
     * @mbggenerated
     */
    int insert(PoorChangeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POOR_CHANGE_RECORD
     *
     * @mbggenerated
     */
    int insertSelective(PoorChangeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POOR_CHANGE_RECORD
     *
     * @mbggenerated
     */
    PoorChangeRecord selectByPrimaryKey(String pcr001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POOR_CHANGE_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PoorChangeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POOR_CHANGE_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PoorChangeRecord record);


    //根据户主id  查询变更记录表
    List<PoorChangeRecord> queryPoorChangeByPcr002(String pcr002);
}