package com.tdkj.dao.InformationCollection;

import com.tdkj.model.PoorLaborForce;
import com.tdkj.model.TechnicalSchools;
import com.tdkj.model.ThsPlf;
import com.tdkj.model.TrainingSituation;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TechnicalSchoolsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technical_schools
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String ths001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technical_schools
     *
     * @mbggenerated
     */
    int insert(TechnicalSchools record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technical_schools
     *
     * @mbggenerated
     */
    int insertSelective(TechnicalSchools record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technical_schools
     *
     * @mbggenerated
     */
    TechnicalSchools selectByPrimaryKey(String ths001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technical_schools
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TechnicalSchools record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technical_schools
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TechnicalSchools record);

    /**
     * 根据劳动力id 查询技工院校信息
     * @param ths002
     * @return
     */
    public List<TechnicalSchools> queryTechnicalSchoolsByThs002(String ths002);


    /**
     * 根据劳动力信息删除技工院校信息
     * @param ths002
     * @return
     */
    public int deleteTechnicalSchoolsByThs002(@Param("ths002")String ths002,@Param("realname")String realname);


    /**
     * 根据行政区划查询劳动力技工院校台账信息
     * @return
     */
    public List<ThsPlf> queryTechnicalSchoolAccountByAab301(@Param("thsPlf")ThsPlf thsPlf, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize);


    /**
     *根据行政区划查询劳动力技工院校总共多条
     * @return
     */
    public String queryAllTechnicalSchoolByAab301(@Param("thsPlf") ThsPlf thsPlf);


    /**
     * 根据劳动力Id 修改isnew=0
     * @param ths002
     * @return
     */
    public int updateIsNewByThs002(@Param("ths002")String ths002);


    /**
     * 批量添加
     * @param list
     * @return
     */
    int addList(@Param("list") List<PoorLaborForce> list);


    //根据劳动力id 查询最新的技工院校信息
    public TechnicalSchools queryNewTechnicalSchools(@Param("ths002")String ths002);
}