package com.tdkj.dao.InformationCollection;

import com.tdkj.model.PoorLaborForce;
import com.tdkj.model.TrainingSituation;
import com.tdkj.model.TsnPlf;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TrainingSituationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String tsn001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    int insert(TrainingSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    int insertSelective(TrainingSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    TrainingSituation selectByPrimaryKey(String tsn001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TrainingSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TrainingSituation record);

    /**
     * 根据劳动力主键查询培训信息
     * @param tsn010
     * @return
     */
    public List<TrainingSituation> queryTrainingSituationByTsn010(String tsn010);


    /**
     * 据劳动力主键删除培训信息
     * @param tsn010
     * @return
     */
    public int deleteTrainingSituationByTsn010(@Param("tsn010")String tsn010,@Param("realname")String realname);


    /**
     * 根据行政区划查询劳动力培训台账信息
     * @return
     */
    public List<TsnPlf> queryTrainSituationAccountByAab301(@Param("tsnPlf")TsnPlf tsnPlf, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize);


    /**
     *根据行政区划查询劳动力培训总共多条
     * @return
     */
    public String queryAllTrainSituationByAab301(@Param("tsnPlf")TsnPlf tsnPlf);


    /**
     * 根据劳动力Id 修改isnew=0
     * @param tsn010
     * @return
     */
    public int updateIsNewByTsn010(@Param("tsn010")String tsn010);

    /**
     * 批量添加
     * @param list
     * @return
     */
    int addList(@Param("list") List<PoorLaborForce> list);

//根据劳动力id 查询最新的培训信息
    public TrainingSituation queryNewTrainSituation(@Param("tsn002")String tsn002);


}