package com.tdkj.service.Param;

import com.tdkj.model.Aa10;

import java.util.List;

/**
 * Created by len on 2019-04-28.
 */
public interface Aa10Service {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa10
     *
     * @mbggenerated
     */
    int insert(Aa10 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa10
     *
     * @mbggenerated
     */
    int insertSelective(Aa10 record);

    /**
     * 根据aaa100查询下拉框中的参数值
     * @param aaa100
     * @return
     */
    List<Aa10> queryAa10ByAaa100(String aaa100);

    /**
     * 根据aaa100查询下拉框中的参数值
     * @param
     * @return
     */
    List<Aa10> queryAllAa10list();


    /**
     * 根据aaa100查询下拉框中的参数值
     * @param aaa100
     * @return
     */
     Aa10 queryAa10ByAaa100Type(String aaa100,String value);

}
