package com.tdkj.service.Param;

import com.tdkj.model.CentralizedSettlements;

import java.util.List;

/**
 * Created by len on 2019-05-16.
 */
public interface CentralizedSettlementsService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTRALIZED_SETTLEMENTS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cts001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTRALIZED_SETTLEMENTS
     *
     * @mbggenerated
     */
    int insert(CentralizedSettlements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTRALIZED_SETTLEMENTS
     *
     * @mbggenerated
     */
    int insertSelective(CentralizedSettlements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTRALIZED_SETTLEMENTS
     *
     * @mbggenerated
     */
    CentralizedSettlements selectByPrimaryKey(String cts001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTRALIZED_SETTLEMENTS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CentralizedSettlements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CENTRALIZED_SETTLEMENTS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CentralizedSettlements record);

    /**
     * 根据aab301 查询安置点名称
     * @param aab301
     * @return
     */
    public List<CentralizedSettlements> queryCentralizedSettlementsByAab301(String aab301);


    /**
     * 集中安置点查询  用于分页
     * @param aab301
     * @return
     */
    public List<CentralizedSettlements> queryAllCentralizedSettlementByAab301(String aab301,String cts002_scan,String startRecord,String pageSize);

    /**
     * 查询有多少个安置点
     * @param aab301
     * @param cts002_scan
     * @return
     */
    public String queryAllByAab301(String aab301,String cts002_scan);

    /**
     * 查询该安置点是有已经被使用
     * @param cts001
     * @return
     */
    public String queryCentralizedSettlementIsInPhd(String cts001);


}
