package com.tdkj.service.InformationCollection;

import com.tdkj.model.EmploymentSituation;
import com.tdkj.model.EysPlf;
import com.tdkj.model.PoorLaborForce;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * Created by len on 2019-04-28.
 */
public interface EmploymentSituationService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String eys001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    int insert(EmploymentSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    int insertSelective(EmploymentSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    EmploymentSituation selectByPrimaryKey(String eys001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmploymentSituation record);
    int updateByPrimaryKeySelectiveKill();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_situation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmploymentSituation record);


    /**
     * 根据劳动力id  查询该劳动力的就业技能
     * @return
     */
    List<EmploymentSituation> queryEmploymentSituationByEys002(String eys002);

    /**
     * 根据劳动力id  查询该劳动力的公益性岗位
     * @return
     */
    List<EmploymentSituation> queryEmploymentSituationByEys002Post(String eys002);




    /**
     * 根据劳动力id  删除该劳动力下的所有就业技能情况
     * @param plf001
     * @return
     */
    int deleteEmploymentSituationByEys002(String eys002, String realname);

    /**
     * 删除所有公益性岗位有关的就业信息
     * @param eys002
     * @param realname
     * @return
     */
    int deletePublicPostByEys002(String eys002, String realname);

    //************************************以下是台账信息**********************************************************************


    /**
     * 根据行政区划查询劳动力就业台账信息
     * @param aab301
     * @return
     */
    List<EysPlf> queryEmploymentSituationAccountByAab301(EysPlf eysPlf, String startRecord, String pageSize);


    /**
     *根据行政区划查询劳动力就业台账总共多条
     * @return
     */
    String queryAllEmploymentSituationByAab301(EysPlf eysPlf);


    /**
     * 根据行政区划查询劳动力公益性岗位台账信息
     * @return
     */
    List<EysPlf> queryPublicPostAccountByAab301(EysPlf eysPlf, String startRecord, String pageSize);


    /**
     *根据行政区划查询劳动力公益性岗位台账总共多条
     * @return
     */
    String queryPublicPostCountByAab301(EysPlf eysPlf);


    /**
     * 根据劳动力Id 修改isnew=0
     * @param eys002
     * @return
     */
    int updateIsNewByEys002(String eys002);

    //根据劳动力id 查询最新的就业信息
    EmploymentSituation queryNewTrainSituation(String eys002);

    /**
     * 计算最新就业创业信息
     *
     * @param plf001
     * @return
     */
    int f_jy_cy(String plf001);


    /**
     * 根据行政区划查询查询劳动力就业培训列表
     * @return
     */
    List<EysPlf> queryEmploymentSituationTrainingByAab301(EysPlf eysPlf, String startRecord, String pageSize);


    /**
     *根据行政区划查询劳动力查询劳动力就业培训列表
     * @return
     */
    String queryAllEmploymentSituationTrainingByAab301(EysPlf eysPlf);



/******************************以下是有问题就业信息查询 ************************************************************************************************************/

    /**
     * 根据行政区划查询劳动力就业台账信息  (有问题数据)
     * @return
     */
    List<EysPlf> queryErrorEmploymentSituationAccountByAab301(EysPlf eysPlf, String startRecord, String pageSize);


    /**
     *根据行政区划查询劳动力就业台账总共多条  (有问题数据)
     * @return
     */
    String queryAllErrorEmploymentSituationByAab301(EysPlf eysPlf);



    //************************************以下是弱劳动力就业台账信息**********************************************************************


    /**
     * 根据行政区划查询弱劳动力就业台账信息
     * @param aab301
     * @return
     */
    List<EysPlf> queryRuoEmploymentSituationAccountByAab301(EysPlf eysPlf, String startRecord, String pageSize);


    /**
     *根据行政区划查询弱劳动力就业台账总共多条
     * @return
     */
    String queryAllRuoEmploymentSituationByAab301(EysPlf eysPlf);


}
