package com.tdkj.service.InformationCollection;

import com.tdkj.model.Entrepreneurship;
import com.tdkj.model.EppPlf;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * Created by len on 2019-04-29.
 */
public interface EntrepreneurshipService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String epp001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    int insert(Entrepreneurship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    int insertSelective(Entrepreneurship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    Entrepreneurship selectByPrimaryKey(String epp001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Entrepreneurship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrepreneurship
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Entrepreneurship record);

    /**
     * 根据劳动力主键查询创业信息
     * @param epp002
     * @return
     */
    List<Entrepreneurship> queryEntrepreneurshipByEpp002(String epp002);


    /**
     * 根据劳动力主键删除创业信息
     * @param epp002
     * @return
     */
    int deleteEntrepreneurshipByEpp002(String epp002, String realname);


    //************************************以下是台账信息**********************************************************************


    /**
     * 根据行政区划查询劳动力创业台账信息
     * @param aab301
     * @return
     */
    List<EppPlf> queryEmploymentShipAccountByAab301(EppPlf eppPlf, String startRecord, String pageSize);


    /**
     *根据行政区划查询劳动力创业台账总共多条
     * @param aab301
     * @return
     */
    String queryAllEmploymentShipByAab301(EppPlf eppPlf);

    /**
     * 根据劳动力Id 修改isnew=0
     * @param epp002
     * @return
     */
    int updateIsNewByEpp002(String epp002);

    //根据劳动力id 查询最新的创业信息
    Entrepreneurship queryNewEntrepreneurship(String epp002);

    /**
     * 计算最新就业创业信息
     *
     * @param plf001
     * @return
     */
    int f_jy_cy(String plf001);
}
