package com.tdkj.service.InformationCollection;

import com.tdkj.model.TrainingSituation;
import com.tdkj.model.TsnPlf;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * Created by len on 2019-04-29.
 */
public interface TrainingSituationService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String tsn001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    int insert(TrainingSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    int insertSelective(TrainingSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    TrainingSituation selectByPrimaryKey(String tsn001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TrainingSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table training_situation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TrainingSituation record);

    /**
     * 根据劳动力主键查询培训信息
     * @param tsn010
     * @return
     */
    public List<TrainingSituation> queryTrainingSituationByTsn010(String tsn010);


    /**
     * 据劳动力主键删除培训信息
     * @param tsn010
     * @return
     */
    public int deleteTrainingSituationByTsn010(String tsn010,String realname);


    //************************************以下是台账信息**********************************************************************


    /**
     * 根据行政区划查询劳动力培训台账信息
     * @param aab301
     * @return
     */
    public List<TsnPlf> queryTrainSituationAccountByAab301(TsnPlf tsnPlf, String startRecord, String pageSize);


    /**
     *根据行政区划查询劳动力创业培训总共多条
     * @param aab301
     * @return
     */
    public String queryAllTrainSituationByAab301(TsnPlf tsnPlf);

    /**
     * 根据劳动力Id 修改isnew=0
     * @param tsn010
     * @return
     */
    public int updateIsNewByTsn010(String tsn010);


    //根据劳动力id 查询最新的培训信息
    public TrainingSituation queryNewTrainSituation(String tsn002);



}
