package com.tdkj.dao.CommunityFactory;

import com.tdkj.model.CommunityFactory;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface CommunityFactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_factory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String ctf001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_factory
     *
     * @mbggenerated
     */
    int insert(CommunityFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_factory
     *
     * @mbggenerated
     */
    int insertSelective(CommunityFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_factory
     *
     * @mbggenerated
     */
    CommunityFactory selectByPrimaryKey(String ctf001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_factory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommunityFactory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_factory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommunityFactory record);

    /**
     * 根据行政区划查询社区工厂信息
     * @return
     */
    public List<CommunityFactory> queryCommunityFactoryByAab301(@Param("communityFactory")CommunityFactory communityFactory, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize);

    /**
     * 根据行政区划查询有多少条数据
     * @return
     */
    public String queryAllByAab301(@Param("communityFactory")CommunityFactory communityFactory);


    //**********************************社区工厂待完善  信息查询******************************************************************************************

    /**
     * 根据行政区划查询   待完善的社区工厂信息
     * @return
     */
    public List<CommunityFactory> querytobeCompleteFactoryByAab301(@Param("communityFactory")CommunityFactory communityFactory, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize);


    /**
     * 根据行政区划查询  待完善的社区工厂  有多少条数据
     * @return
     */
    public String queryAlltobeCompleteFactoryByAab301(@Param("communityFactory")CommunityFactory communityFactory);


}