package com.tdkj.dao.CreditVillage;

import com.tdkj.model.CreditVillage;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface CreditVillageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cvg001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    int insert(CreditVillage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    int insertSelective(CreditVillage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    CreditVillage selectByPrimaryKey(String cvg001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CreditVillage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_village
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CreditVillage record);

    /**
     * 根据aab301 查询信用乡村信息
     * @param aab301
     * @return
     */
    public List<CreditVillage> queryCreditVillageByAab301(@Param("creditVillage")CreditVillage creditVillage, @Param("startRecord")String startRecord, @Param("pageSize")String pageSize) ;


    /**
     * 根据行政区划查询总条数
     * @param aab301
     * @return
     */
    public String queryAllByAab301(@Param("creditVillage")CreditVillage creditVillage);

}