package com.tdkj.service.UserManager;

import com.tdkj.model.FpUser;
import com.tdkj.model.SysRole;

import java.util.List;

/**
 * Created by len on 2019-05-03.
 */
public interface FpUserService {


    List<SysRole>  findRole(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FP_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FP_USER
     *
     * @mbggenerated
     */
    int insert(FpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FP_USER
     *
     * @mbggenerated
     */
    int insertSelective(FpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FP_USER
     *
     * @mbggenerated
     */
    FpUser selectByPrimaryKey(String id);


    FpUser selectIdcard(String idcard,String mobilephome);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FP_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FP_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FpUser record);


    /**
     * 根据行政区划查询user用户数量
     * @return
     */
    public String countUserByAab301(String aab301);

    /**
     * 根据用户名查询该用户是否已经存在
     * @return
     */
    public FpUser queryUserByUserName(String username);

    /**
     * 根据用户名密码登录系统
     * @return
     */
    public FpUser LoginByUserNameAndPwd(String username,String password);



    /**
     * 根据aab301 查询用户信息
     * @param aab301
     * @return
     */
    public List<FpUser> queryFpUserByAab301(String aab301, String username, String realname, String idcard, String startRecord, String pageSize);

    /**
     * 根据行政区划查询 总条数
     * @param aab301
     * @return
     */
    public String queryAllByAab301(String aab301, String username, String realname, String idcard);

}
