package com.tdkj.service.UserManager;

import com.tdkj.model.User;

/**
 * Created by len on 2019-04-30.
 */
public interface UserService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据行政区划撤销user用户数量
     * @return
     */
    public int countUserByAab301(String aab301);

    /**
     * 根据用户名查询该用户是否已经存在
     * @return
     */
    public User queryUserByUserName(String username);

    /**
     * 根据用户名密码登录系统
     * @return
     */
    public User LoginByUserNameAndPwd(String username,String password);
}
