package com.tdkj.dao.Ztree;

import com.tdkj.model.EmXzqView;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface EmXzqViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_xzq_view
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String xzqId5);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_xzq_view
     *
     * @mbggenerated
     */
    int insert(EmXzqView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_xzq_view
     *
     * @mbggenerated
     */
    int insertSelective(EmXzqView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_xzq_view
     *
     * @mbggenerated
     */
    EmXzqView selectByPrimaryKey(String xzqId5);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_xzq_view
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmXzqView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_xzq_view
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmXzqView record);

    /**
     * 查询树型菜单数据
     * @param parentid
     * @return
     */
    public List<EmXzqView> getAllGroupList(String parentid);
}