package com.tdkj.dao.Ztree;

import com.tdkj.model.PoorHouseholdTranslation;
import com.tdkj.model.PoorXzqh;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface PoorXzqhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POOR_XZQH
     *
     * @mbggenerated
     */
    int insert(PoorXzqh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POOR_XZQH
     *
     * @mbggenerated
     */
    int insertSelective(PoorXzqh record);

    /**
     * 查询树菜单
     * @param parentid
     * @return
     */
     List<PoorXzqh> getAllGroupList(@Param("parentid") String parentid, @Param("first")String first,@Param("menutype")String menutype);


    /**
     * 查询级别
     * @param parentid
     * @return
     */
     PoorXzqh queryPoorXzqhSub(String parentid);


     List<PoorXzqh> queryPoorXzqh();

    /**
     * 查询市区街道
     * @return
     */
     List<PoorXzqh> queryArea(@Param("xzqhbm")String xzqhbm);

    /**
     * 根据id  查询所下级  包括村子
     * @param xzqhbm
     * @return
     */
    public List<PoorXzqh> queryAreaByPid(@Param("xzqhbm")String xzqhbm);



    /**
     *
     */
     List<PoorXzqh> getAllPoorWorkGroupList();

    /**
     * 根据aab301查询编码info
     * @param aab301
     * @return
     */
     PoorXzqh queryAab301Info(@Param("aab301")String aab301);

    /**
     * 根据aab301查询编码info
     * @param aab301
     * @return
     */
    @Select("select poor_hu,worker,confirm_poor_hu,confirm_worker, aab301 from ZTREE_PER_COUNT t  where aab301=#{aab301}")
    PoorXzqh queryAab301Count(@Param("aab301")String aab301);


   //贫困户统计
    List<PoorHouseholdTranslation> queryAllByAab301Statistics(@Param("aab301")String aab301,@Param("phd012")String phd012,@Param("phd013")String phd013,@Param("phd014")String phd014,@Param("len2") String len2,@Param("len1") String len1);

    //易地搬迁统计
    List<PoorHouseholdTranslation> RelocationqueryAllByAab301Statistics(@Param("aab301")String aab301,@Param("phd012")String phd012,@Param("phd013")String phd013,@Param("phd014")String phd014,@Param("len2") String len2,@Param("len1") String len1);

    //就业统计
    List<PoorHouseholdTranslation> EploymentqueryAllByAab301Statistics(@Param("aab301")String aab301,@Param("phd012")String phd012,@Param("phd013")String phd013,@Param("phd014")String phd014,@Param("len2") String len2,@Param("len1") String len1);

    //苏陕协作统计
    List<PoorHouseholdTranslation> CooperationqueryAllByAab301Statistics(@Param("aab301")String aab301,@Param("phd012")String phd012,@Param("phd013")String phd013,@Param("phd014")String phd014,@Param("len2") String len2,@Param("len1") String len1);

    //综合统计
    List<PoorHouseholdTranslation> ComprehensivequeryAllByAab301Statistics(@Param("aab301")String aab301,@Param("phd012")String phd012,@Param("phd013")String phd013,@Param("phd014")String phd014,@Param("len2") String len2,@Param("len1") String len1);


   //辖区区域数量查询
    @Select("select count(1) from POOR_HOUSEHOLD_TRANSLATION t where (parentid=#{aab301} or aab301=#{aab301})")
    String queryAllByAab301(String aab301);


    /**
     * 根据aab301  查询information 中的信息
     * @param poorXzqh
     * @return
     */
    public List<PoorXzqh> queryInformationByAab301(@Param("poorXzqh")PoorXzqh poorXzqh,@Param("startRecord")String startRecord,@Param("pageSize")String pageSize);

    /**
     * 查询information 的个数
     * @param poorXzqh
     * @return
     */
    public String queryAllInformationByAab301(@Param("poorXzqh")PoorXzqh poorXzqh);

}