package com.tdkj.service.IncubatorBase;

import com.tdkj.model.IncubatorBase;

import java.util.List;

/**
 * Created by len on 2019-04-29.
 */
public interface IncubatorBaseService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incubator_base
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String ibb001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incubator_base
     *
     * @mbggenerated
     */
    int insert(IncubatorBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incubator_base
     *
     * @mbggenerated
     */
    int insertSelective(IncubatorBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incubator_base
     *
     * @mbggenerated
     */
    IncubatorBase selectByPrimaryKey(String ibb001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incubator_base
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IncubatorBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incubator_base
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IncubatorBase record);


    /**
     * 根据aab301 查询创业基地园区中心
     */
    public List<IncubatorBase> queryIncubatorBaseByAab301(IncubatorBase incubatorBase, String startRecord, String pageSize);

    /**
     * 根据行政区划查询总条数
     * @param aab301
     * @return
     */
    public String queryAllByAab301(IncubatorBase incubatorBase);
}
